/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.RutasJpaController;
import java.awt.BorderLayout;
import java.awt.FlowLayout;

/**
 *
 * @author juandapp
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     *
     */
    int tipo_u;
    String tipo_e;
    String usuario_id;

    public GUI() {
        initComponents();
        jPPrincipal.setLayout(new FlowLayout());
//        setResizable(false);
    }
    
    //pasajeros
    public GUI(int tipo, String usuario_id){
        initComponents();
        setVisible(true);
        jPPrincipal.setLayout(new FlowLayout());
        this.tipo_u=tipo;
        this.usuario_id = usuario_id;
      
        jPPrincipal.setLayout(new FlowLayout());
        //PASAJEROS
        if(tipo_u==1){            
            jMILoginPasajeros.setEnabled(false);
            jMEmpleado.setEnabled(false);
            jMISalirP.setEnabled(true);
            jMIModificarDatos.setEnabled(true);
            jMITarjetaPasajero.setEnabled(true);
            jMIMisReclamos.setEnabled(true);
            jMIRutasPasajero.setEnabled(true);
            jMIModificarDatos.doClick();
          
        }
        
        
       
    }

    //EMPLEADOS
    public GUI(int valor, String usuario_id, String tipo) {


        initComponents();
        setVisible(true);
        jPPrincipal.setLayout(new FlowLayout());
        tipo_e = tipo;
        tipo_u=valor;
        this.usuario_id = usuario_id;
        
        if (tipo_u == 2) { 
            jMPasajero.setEnabled(false);
            jMISalirE.setEnabled(true);
            jMILoginEmpleado.setEnabled(false);
            if(tipo_e.equals("Auxiliar")){
                
                jMAuxiliar.setEnabled(true);
            }
            if(tipo_e.equals("Conductor")){
                jMConductor.setEnabled(true);
            }
            if(tipo_e.equals("DEstacion")){
                jMDirectorEstacion.setEnabled(true);
            }
            if(tipo_e.equals("Operativo")){
                jMDirectoresOperativos.setEnabled(true);
            }
                
            
            
        }

//        if (tipo_e == 2) { //El usuario es Vendedor
//            jMReportes.setEnabled(false);
//            jMIBuses.setEnabled(false);
//            jMIEstacion.setEnabled(false);
//        }
//        if (tipo_e == 3) { //El usuario es jefe de taller
//            jMReportes.setEnabled(false);
//            jMVentas.setEnabled(false);
//            jMIRutas.setEnabled(false);
//            jMIBuses.setEnabled(false);
//
//        }


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPPrincipal = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMPasajero = new javax.swing.JMenu();
        jMILoginPasajeros = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMIModificarDatos = new javax.swing.JMenuItem();
        jMITarjetaPasajero = new javax.swing.JMenuItem();
        jMIMisReclamos = new javax.swing.JMenuItem();
        jMIRutasPasajero = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMISalirP = new javax.swing.JMenuItem();
        jMEmpleado = new javax.swing.JMenu();
        jMILoginEmpleado = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMDirectoresOperativos = new javax.swing.JMenu();
        jMIEmpleadosInfo = new javax.swing.JMenuItem();
        jMIRutas = new javax.swing.JMenuItem();
        jMIBuses = new javax.swing.JMenuItem();
        jMIEstacion = new javax.swing.JMenuItem();
        jMICrearTurnos = new javax.swing.JMenuItem();
        jMIReportes = new javax.swing.JMenuItem();
        jMAuxiliar = new javax.swing.JMenu();
        jMICrearPasajero = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMICrearCotizacion = new javax.swing.JMenuItem();
        JMIReclamo = new javax.swing.JMenuItem();
        jMDirectorEstacion = new javax.swing.JMenu();
        jMIReclamoConsultar = new javax.swing.JMenuItem();
        jMConductor = new javax.swing.JMenu();
        jMIMisTurnos = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMISalirE = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPPrincipal.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.png"))); // NOI18N
        jPPrincipal.add(jLabel2);
        jLabel2.setBounds(0, 0, 670, 480);

        jMPasajero.setText("Pasajeros");

        jMILoginPasajeros.setText("Login");
        jMILoginPasajeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMILoginPasajerosActionPerformed(evt);
            }
        });
        jMPasajero.add(jMILoginPasajeros);
        jMPasajero.add(jSeparator2);

        jMIModificarDatos.setText("Modificar Datos");
        jMIModificarDatos.setEnabled(false);
        jMIModificarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIModificarDatosActionPerformed(evt);
            }
        });
        jMPasajero.add(jMIModificarDatos);

        jMITarjetaPasajero.setText("Info de Tarjeta");
        jMITarjetaPasajero.setEnabled(false);
        jMITarjetaPasajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMITarjetaPasajeroActionPerformed(evt);
            }
        });
        jMPasajero.add(jMITarjetaPasajero);

        jMIMisReclamos.setText("Mis Reclamos");
        jMIMisReclamos.setEnabled(false);
        jMIMisReclamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIMisReclamosActionPerformed(evt);
            }
        });
        jMPasajero.add(jMIMisReclamos);

        jMIRutasPasajero.setText("Consultar Rutas");
        jMIRutasPasajero.setEnabled(false);
        jMIRutasPasajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIRutasPasajeroActionPerformed(evt);
            }
        });
        jMPasajero.add(jMIRutasPasajero);
        jMPasajero.add(jSeparator6);

        jMISalirP.setText("Salir");
        jMISalirP.setEnabled(false);
        jMISalirP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMISalirPActionPerformed(evt);
            }
        });
        jMPasajero.add(jMISalirP);

        jMenuBar1.add(jMPasajero);

        jMEmpleado.setText("Empleados");

        jMILoginEmpleado.setText("Login");
        jMILoginEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMILoginEmpleadoActionPerformed(evt);
            }
        });
        jMEmpleado.add(jMILoginEmpleado);
        jMEmpleado.add(jSeparator5);

        jMDirectoresOperativos.setText("Director Operativo");
        jMDirectoresOperativos.setEnabled(false);

        jMIEmpleadosInfo.setText("Manejo Empleados");
        jMIEmpleadosInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIEmpleadosInfoActionPerformed(evt);
            }
        });
        jMDirectoresOperativos.add(jMIEmpleadosInfo);

        jMIRutas.setText("Rutas");
        jMIRutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIRutasActionPerformed(evt);
            }
        });
        jMDirectoresOperativos.add(jMIRutas);

        jMIBuses.setText("Buses");
        jMIBuses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIBusesActionPerformed(evt);
            }
        });
        jMDirectoresOperativos.add(jMIBuses);

        jMIEstacion.setText("Estaciones");
        jMIEstacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIEstacionActionPerformed(evt);
            }
        });
        jMDirectoresOperativos.add(jMIEstacion);

        jMICrearTurnos.setText("Programar Turnos");
        jMICrearTurnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMICrearTurnosActionPerformed(evt);
            }
        });
        jMDirectoresOperativos.add(jMICrearTurnos);

        jMIReportes.setText("Reportes");
        jMIReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIReportesActionPerformed(evt);
            }
        });
        jMDirectoresOperativos.add(jMIReportes);

        jMEmpleado.add(jMDirectoresOperativos);

        jMAuxiliar.setText("Auxiliar");
        jMAuxiliar.setEnabled(false);

        jMICrearPasajero.setText("Registrar Pasajero");
        jMICrearPasajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMICrearPasajeroActionPerformed(evt);
            }
        });
        jMAuxiliar.add(jMICrearPasajero);

        jMenuItem1.setText("Tarjetas Genericas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMAuxiliar.add(jMenuItem1);

        jMenuItem2.setText("Tarjetas Personalizadas");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMAuxiliar.add(jMenuItem2);

        jMICrearCotizacion.setText("Registrar Venta");
        jMICrearCotizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMICrearCotizacionActionPerformed(evt);
            }
        });
        jMAuxiliar.add(jMICrearCotizacion);

        JMIReclamo.setText("Reclamos");
        JMIReclamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIReclamoActionPerformed(evt);
            }
        });
        jMAuxiliar.add(JMIReclamo);

        jMEmpleado.add(jMAuxiliar);

        jMDirectorEstacion.setText("Director Estacion");
        jMDirectorEstacion.setEnabled(false);

        jMIReclamoConsultar.setText("Ver Reclamos");
        jMIReclamoConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIReclamoConsultarActionPerformed(evt);
            }
        });
        jMDirectorEstacion.add(jMIReclamoConsultar);

        jMEmpleado.add(jMDirectorEstacion);

        jMConductor.setText("Conductor");
        jMConductor.setEnabled(false);

        jMIMisTurnos.setText("Mis Turnos");
        jMIMisTurnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIMisTurnosActionPerformed(evt);
            }
        });
        jMConductor.add(jMIMisTurnos);

        jMEmpleado.add(jMConductor);
        jMEmpleado.add(jSeparator7);

        jMISalirE.setText("Salir");
        jMISalirE.setEnabled(false);
        jMISalirE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMISalirEActionPerformed(evt);
            }
        });
        jMEmpleado.add(jMISalirE);

        jMenuBar1.add(jMEmpleado);

        jMenu1.setText("Movilizacion");

        jMenuItem4.setText("Simular Viaje");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Info");

        jMenuItem3.setText("Hecho Por");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMIRutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIRutasActionPerformed
        ///interfaz completa
        try {
            jPPrincipal.removeAll();
        } catch (Exception e) {
        }
         
        JPRuta jPRR = new JPRuta();
        jPPrincipal.add(jPRR, BorderLayout.CENTER);
        jPPrincipal.updateUI();
        this.pack();
    }//GEN-LAST:event_jMIRutasActionPerformed

    private void jMIEstacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIEstacionActionPerformed
        try {
            jPPrincipal.removeAll();
        } catch (Exception e) {
        }
      JPEstacion jPO = new JPEstacion();
        jPPrincipal.add(jPO, BorderLayout.CENTER);
        jPPrincipal.updateUI();
        this.pack();
    }//GEN-LAST:event_jMIEstacionActionPerformed

    private void jMICrearCotizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMICrearCotizacionActionPerformed
        try {
            jPPrincipal.removeAll();
        } catch (Exception e) {
        }
        JPVentaTarjetas jPC2 = new JPVentaTarjetas();
        jPPrincipal.add(jPC2, BorderLayout.CENTER);
        jPPrincipal.updateUI();
        this.pack();
    }//GEN-LAST:event_jMICrearCotizacionActionPerformed

    private void jMIBusesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIBusesActionPerformed
        ///interfaz completa
        try {
            jPPrincipal.removeAll();
        } catch (Exception e) {
        }
        JPBus jPB = new JPBus();
        jPPrincipal.add(jPB, BorderLayout.CENTER);
        jPPrincipal.updateUI();
        this.pack();
    }//GEN-LAST:event_jMIBusesActionPerformed

    private void jMICrearTurnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMICrearTurnosActionPerformed
        try {
            jPPrincipal.removeAll();
        } catch (Exception e) {
        }
        JPProgramarTurnos jPE = new JPProgramarTurnos();
        jPPrincipal.add(jPE, BorderLayout.CENTER);
        jPPrincipal.updateUI();
        this.pack();
    }//GEN-LAST:event_jMICrearTurnosActionPerformed

    private void jMILoginPasajerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMILoginPasajerosActionPerformed
        
        JFLogin login=new JFLogin(1);
        setVisible(false);
        
    }//GEN-LAST:event_jMILoginPasajerosActionPerformed

    private void JMIReclamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIReclamoActionPerformed
       try {
            jPPrincipal.removeAll();
        } catch (Exception e) {
        }
        JPReclamo g = new JPReclamo(2,usuario_id, "EMPLEADO");
        g.setBounds(jPPrincipal.getBounds());
        jPPrincipal.add(g, BorderLayout.CENTER);
        jPPrincipal.updateUI();
        this.pack();
    }//GEN-LAST:event_JMIReclamoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        try {
            jPPrincipal.removeAll();
        } catch (Exception e) {
        }
        JPTarjetasGenericas tg = new JPTarjetasGenericas();
        tg.setBounds(jPPrincipal.getBounds());
        jPPrincipal.add(tg, BorderLayout.CENTER);
        jPPrincipal.updateUI();
        this.pack();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        try {
            jPPrincipal.removeAll();
        } catch (Exception e) {
        }
        JPTarjetasPersonalizadas tg = new JPTarjetasPersonalizadas();
        tg.setBounds(jPPrincipal.getBounds());
        jPPrincipal.add(tg, BorderLayout.CENTER);
        jPPrincipal.updateUI();
        this.pack();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMIModificarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIModificarDatosActionPerformed
        try {
            jPPrincipal.removeAll();
        } catch (Exception e) {
        }
        JPPasajero g = new JPPasajero(1, usuario_id);
        g.setBounds(jPPrincipal.getBounds());
        jPPrincipal.add(g, BorderLayout.CENTER);
        jPPrincipal.updateUI();
        this.pack();
    }//GEN-LAST:event_jMIModificarDatosActionPerformed

    private void jMITarjetaPasajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMITarjetaPasajeroActionPerformed
         try {
            jPPrincipal.removeAll();
        } catch (Exception e) {
        }
        JPVentaTarjetas tg = new JPVentaTarjetas(1, usuario_id);
        tg.setBounds(jPPrincipal.getBounds());
        jPPrincipal.add(tg, BorderLayout.CENTER);
        jPPrincipal.updateUI();
        this.pack();
    }//GEN-LAST:event_jMITarjetaPasajeroActionPerformed

    private void jMIMisReclamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIMisReclamosActionPerformed
        try {
            jPPrincipal.removeAll();
        } catch (Exception e) {
        }
        JPReclamo g = new JPReclamo(1, usuario_id);
        g.setBounds(jPPrincipal.getBounds());
        jPPrincipal.add(g, BorderLayout.CENTER);
        jPPrincipal.updateUI();
        this.pack();
    }//GEN-LAST:event_jMIMisReclamosActionPerformed

    private void jMIRutasPasajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIRutasPasajeroActionPerformed
        try {
            jPPrincipal.removeAll();
        } catch (Exception e) {
        }
         
        JPRuta jPRR = new JPRuta(1);
        jPPrincipal.add(jPRR, BorderLayout.CENTER);
        jPPrincipal.updateUI();
        this.pack();
    }//GEN-LAST:event_jMIRutasPasajeroActionPerformed

    private void jMILoginEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMILoginEmpleadoActionPerformed
        JFLogin login=new JFLogin(2);
        setVisible(false);
    }//GEN-LAST:event_jMILoginEmpleadoActionPerformed

    private void jMIEmpleadosInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIEmpleadosInfoActionPerformed
      try {
            jPPrincipal.removeAll();
        } catch (Exception e) {
        }
        JPEmpleado jPE = new JPEmpleado();
        jPPrincipal.add(jPE, BorderLayout.CENTER);
        jPPrincipal.updateUI();
        this.pack();
    }//GEN-LAST:event_jMIEmpleadosInfoActionPerformed

    private void jMIReclamoConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIReclamoConsultarActionPerformed
        try {
            jPPrincipal.removeAll();
        } catch (Exception e) {
        }
        JPReclamo g = new JPReclamo(3,usuario_id, "EMPLEADO");
        g.setBounds(jPPrincipal.getBounds());
        jPPrincipal.add(g, BorderLayout.CENTER);
        jPPrincipal.updateUI();
        this.pack();
    }//GEN-LAST:event_jMIReclamoConsultarActionPerformed

    private void jMISalirPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMISalirPActionPerformed
        setVisible(false);
        GUI nueva=new GUI();
        nueva.setVisible(true);
    }//GEN-LAST:event_jMISalirPActionPerformed

    private void jMISalirEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMISalirEActionPerformed
        // TODO add your handling code here:
         setVisible(false);
        GUI nueva=new GUI();
        nueva.setVisible(true);
    }//GEN-LAST:event_jMISalirEActionPerformed

    private void jMICrearPasajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMICrearPasajeroActionPerformed
        // TODO add your handling code here:
         try {
            jPPrincipal.removeAll();
        } catch (Exception e) {
        }
        JPPasajero g = new JPPasajero();
        g.setBounds(jPPrincipal.getBounds());
        jPPrincipal.add(g, BorderLayout.CENTER);
        jPPrincipal.updateUI();
        this.pack();
    }//GEN-LAST:event_jMICrearPasajeroActionPerformed

    private void jMIMisTurnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIMisTurnosActionPerformed
        try {
            jPPrincipal.removeAll();
        } catch (Exception e) {
        }
        JPProgramarTurnos jPE = new JPProgramarTurnos(1, usuario_id);
        jPPrincipal.add(jPE, BorderLayout.CENTER);
        jPPrincipal.updateUI();
        this.pack();
    }//GEN-LAST:event_jMIMisTurnosActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        JFIntegrantes gui=new JFIntegrantes();
        gui.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMIReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIReportesActionPerformed
        // TODO add your handling code here:
                try {
            jPPrincipal.removeAll();
        } catch (Exception e) {
        }
        JPReportes jPr = new JPReportes();
        jPPrincipal.add(jPr, BorderLayout.CENTER);
        jPPrincipal.updateUI();
        this.pack();
    }//GEN-LAST:event_jMIReportesActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
                  try {
            jPPrincipal.removeAll();
        } catch (Exception e) {
        }
        JPMovilizacion jPr = new JPMovilizacion();
        jPPrincipal.add(jPr, BorderLayout.CENTER);
        jPPrincipal.updateUI();
        this.pack();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new GUI().setVisible(true);

            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JMIReclamo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMAuxiliar;
    private javax.swing.JMenu jMConductor;
    private javax.swing.JMenu jMDirectorEstacion;
    private javax.swing.JMenu jMDirectoresOperativos;
    private javax.swing.JMenu jMEmpleado;
    private javax.swing.JMenuItem jMIBuses;
    private javax.swing.JMenuItem jMICrearCotizacion;
    private javax.swing.JMenuItem jMICrearPasajero;
    private javax.swing.JMenuItem jMICrearTurnos;
    private javax.swing.JMenuItem jMIEmpleadosInfo;
    private javax.swing.JMenuItem jMIEstacion;
    private javax.swing.JMenuItem jMILoginEmpleado;
    private javax.swing.JMenuItem jMILoginPasajeros;
    private javax.swing.JMenuItem jMIMisReclamos;
    private javax.swing.JMenuItem jMIMisTurnos;
    private javax.swing.JMenuItem jMIModificarDatos;
    private javax.swing.JMenuItem jMIReclamoConsultar;
    private javax.swing.JMenuItem jMIReportes;
    private javax.swing.JMenuItem jMIRutas;
    private javax.swing.JMenuItem jMIRutasPasajero;
    private javax.swing.JMenuItem jMISalirE;
    private javax.swing.JMenuItem jMISalirP;
    private javax.swing.JMenuItem jMITarjetaPasajero;
    private javax.swing.JMenu jMPasajero;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPPrincipal;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    // End of variables declaration//GEN-END:variables
}
