/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import controladores.ControladorRuta;

import controladores.ControladorBus;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.*;
import entidades.Buses;
import entidades.Rutas;

/**
 *
 * @author Juan
 */
public class JPBus extends javax.swing.JPanel {

    /**
     * Creates new form JPBus
     */
    ControladorBus controladorBus;
    ControladorRuta controladorRuta;

    public JPBus() {
        initComponents();
        controladorBus = new ControladorBus();
        controladorRuta = new ControladorRuta();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTPBus = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTFCapacidad1 = new javax.swing.JTextField();
        jTFPlaca1 = new javax.swing.JTextField();
        jBLimpiar1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jTFChasis1 = new javax.swing.JTextField();
        jTFMarca1 = new javax.swing.JTextField();
        jBCrear1 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jTFAsientos1 = new javax.swing.JTextField();
        jCBTipo1 = new javax.swing.JComboBox();
        jCBRuta1 = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jBLimpiarConsultar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTResultados = new javax.swing.JTable();
        jBConsultar1 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jTFPlaca2 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jTFCapacidad2 = new javax.swing.JTextField();
        jCBTipo2 = new javax.swing.JComboBox();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jCBRuta2 = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jBModificar = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jTFPlaca3 = new javax.swing.JTextField();
        jTFMarca3 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jTFChasis3 = new javax.swing.JTextField();
        jTFAsientos3 = new javax.swing.JTextField();
        jTFCapacidad3 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jCBTipo3 = new javax.swing.JComboBox();
        jCBRuta3 = new javax.swing.JComboBox();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Bus"));

        jPanel7.setLayout(null);

        jPanel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.setLayout(null);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Tipo");
        jPanel8.add(jLabel11);
        jLabel11.setBounds(0, 170, 60, 30);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Placa");
        jPanel8.add(jLabel12);
        jLabel12.setBounds(-10, 10, 80, 30);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Marca");
        jPanel8.add(jLabel13);
        jLabel13.setBounds(-30, 50, 120, 30);

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Nro. Asientos");
        jPanel8.add(jLabel14);
        jLabel14.setBounds(10, 130, 80, 40);

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Capacidad");
        jPanel8.add(jLabel15);
        jLabel15.setBounds(150, 130, 80, 40);
        jPanel8.add(jTFCapacidad1);
        jTFCapacidad1.setBounds(230, 130, 50, 30);
        jPanel8.add(jTFPlaca1);
        jTFPlaca1.setBounds(100, 10, 180, 30);

        jBLimpiar1.setText("Limpiar");
        jBLimpiar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiar1ActionPerformed(evt);
            }
        });
        jPanel8.add(jBLimpiar1);
        jBLimpiar1.setBounds(100, 270, 70, 23);

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Nro. Chasis");
        jPanel8.add(jLabel16);
        jLabel16.setBounds(-10, 90, 110, 30);
        jPanel8.add(jTFChasis1);
        jTFChasis1.setBounds(100, 90, 180, 30);
        jPanel8.add(jTFMarca1);
        jTFMarca1.setBounds(100, 50, 180, 30);

        jBCrear1.setText("Crear");
        jBCrear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCrear1ActionPerformed(evt);
            }
        });
        jPanel8.add(jBCrear1);
        jBCrear1.setBounds(220, 270, 59, 23);

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Ruta");
        jPanel8.add(jLabel28);
        jLabel28.setBounds(-10, 220, 90, 30);
        jPanel8.add(jTFAsientos1);
        jTFAsientos1.setBounds(100, 130, 50, 30);

        jCBTipo1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Troncal", "Alimentador", "Padron" }));
        jPanel8.add(jCBTipo1);
        jCBTipo1.setBounds(100, 170, 180, 30);

        jCBRuta1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));
        jCBRuta1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jCBRuta1PopupMenuWillBecomeVisible(evt);
            }
        });
        jPanel8.add(jCBRuta1);
        jCBRuta1.setBounds(100, 220, 180, 30);

        jPanel7.add(jPanel8);
        jPanel8.setBounds(0, 0, 420, 310);

        jTPBus.addTab("Crear", jPanel7);

        jPanel3.setLayout(null);

        jPanel9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel9.setLayout(null);

        jBLimpiarConsultar.setText("Limpiar");
        jBLimpiarConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarConsultarActionPerformed(evt);
            }
        });
        jPanel9.add(jBLimpiarConsultar);
        jBLimpiarConsultar.setBounds(290, 100, 90, 23);

        jTResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Placa", "Marca", "Chasis", "Tipo", "Nro. Asientos", "Capacidad", "Ruta"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTResultados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTResultadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTResultados);

        jPanel9.add(jScrollPane1);
        jScrollPane1.setBounds(10, 210, 410, 100);

        jBConsultar1.setText("Consultar");
        jBConsultar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsultar1ActionPerformed(evt);
            }
        });
        jPanel9.add(jBConsultar1);
        jBConsultar1.setBounds(290, 140, 90, 23);

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Placa");
        jPanel9.add(jLabel23);
        jLabel23.setBounds(-10, 10, 80, 30);
        jPanel9.add(jTFPlaca2);
        jTFPlaca2.setBounds(80, 10, 180, 30);

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Capacidad");
        jPanel9.add(jLabel27);
        jLabel27.setBounds(0, 40, 80, 40);
        jPanel9.add(jTFCapacidad2);
        jTFCapacidad2.setBounds(80, 50, 180, 30);

        jCBTipo2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Troncal", "Alimentador", "Padron" }));
        jPanel9.add(jCBTipo2);
        jCBTipo2.setBounds(80, 90, 180, 30);

        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("Tipo");
        jPanel9.add(jLabel33);
        jLabel33.setBounds(0, 90, 60, 30);

        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("Ruta");
        jPanel9.add(jLabel34);
        jLabel34.setBounds(-10, 130, 90, 30);

        jCBRuta2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cargar" }));
        jCBRuta2.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jCBRuta2PopupMenuWillBecomeVisible(evt);
            }
        });
        jPanel9.add(jCBRuta2);
        jCBRuta2.setBounds(80, 130, 180, 30);

        jPanel3.add(jPanel9);
        jPanel9.setBounds(0, 0, 590, 340);

        jTPBus.addTab("Consultar", jPanel3);

        jPanel4.setLayout(null);

        jPanel10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel10.setLayout(null);

        jBModificar.setText("Modificar");
        jBModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarActionPerformed(evt);
            }
        });
        jPanel10.add(jBModificar);
        jBModificar.setBounds(170, 270, 110, 23);

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Placa");
        jPanel10.add(jLabel24);
        jLabel24.setBounds(-10, 10, 80, 30);

        jTFPlaca3.setEditable(false);
        jPanel10.add(jTFPlaca3);
        jTFPlaca3.setBounds(100, 10, 180, 30);
        jPanel10.add(jTFMarca3);
        jTFMarca3.setBounds(100, 50, 180, 30);

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Marca");
        jPanel10.add(jLabel25);
        jLabel25.setBounds(-30, 50, 120, 30);

        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Nro. Chasis");
        jPanel10.add(jLabel26);
        jLabel26.setBounds(-10, 90, 110, 30);
        jPanel10.add(jTFChasis3);
        jTFChasis3.setBounds(100, 90, 180, 30);
        jPanel10.add(jTFAsientos3);
        jTFAsientos3.setBounds(100, 130, 50, 30);
        jPanel10.add(jTFCapacidad3);
        jTFCapacidad3.setBounds(230, 130, 50, 30);

        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Nro. Asientos");
        jPanel10.add(jLabel29);
        jLabel29.setBounds(10, 130, 80, 40);

        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Tipo");
        jPanel10.add(jLabel30);
        jLabel30.setBounds(0, 170, 60, 30);

        jCBTipo3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Troncal", "Alimentador", "Padron" }));
        jPanel10.add(jCBTipo3);
        jCBTipo3.setBounds(100, 170, 180, 30);

        jCBRuta3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cargar" }));
        jCBRuta3.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jCBRuta3PopupMenuWillBecomeVisible(evt);
            }
        });
        jCBRuta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBRuta3ActionPerformed(evt);
            }
        });
        jPanel10.add(jCBRuta3);
        jCBRuta3.setBounds(100, 220, 180, 30);

        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("Ruta");
        jPanel10.add(jLabel35);
        jLabel35.setBounds(-10, 220, 90, 30);

        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("Capacidad");
        jPanel10.add(jLabel36);
        jLabel36.setBounds(150, 130, 80, 40);

        jPanel4.add(jPanel10);
        jPanel10.setBounds(0, 10, 450, 320);

        jTPBus.addTab("Modificar", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTPBus, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTPBus, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBLimpiar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiar1ActionPerformed
        limpiarCamposCrear();
    }//GEN-LAST:event_jBLimpiar1ActionPerformed

    private void jBCrear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCrear1ActionPerformed

        int guardar = -1;
        try {

            String placa = jTFPlaca1.getText();
            String marca = jTFMarca1.getText();
            String chasis = jTFChasis1.getText();
            String tipo = jCBTipo1.getSelectedItem().toString();
            int asientos = Integer.parseInt(jTFAsientos1.getText());
            int capacidad = Integer.parseInt(jTFCapacidad1.getText());
            String r = jCBRuta1.getSelectedItem().toString();
            Rutas ruta = controladorRuta.consultar(r);
            guardar = controladorBus.insertar(placa, marca, chasis, tipo, asientos, capacidad, ruta);

        } catch (Exception e) {
        }
        if (guardar == -1) {
            JOptionPane.showMessageDialog(this, "No se pudo crear ", "Error Base Datos", JOptionPane.ERROR_MESSAGE);
        } else {

            if (guardar == 1) {

                JOptionPane.showMessageDialog(this, "Ya existe el Bus ", "Error", ERROR);


            } else {
                JOptionPane.showMessageDialog(this, "Bus Creado correctamente", "Sistema", JOptionPane.INFORMATION_MESSAGE);

                limpiarCamposConsultar();
                jTFPlaca2.setText(jTFPlaca1.getText());
                jBConsultar1.doClick();
                jTPBus.setSelectedIndex(1);
                limpiarCamposCrear();
            }
        }
    }//GEN-LAST:event_jBCrear1ActionPerformed

    private void jBLimpiarConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarConsultarActionPerformed
        limpiarCamposConsultar();
    }//GEN-LAST:event_jBLimpiarConsultarActionPerformed

    private void jTResultadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTResultadosMouseClicked

        int selectedRow = jTResultados.getSelectedRow();
        jCBRuta3.setModel(
                new javax.swing.DefaultComboBoxModel(controladorRuta.listar()));
        jTFPlaca3.setText("" + jTResultados.getModel().getValueAt(selectedRow, 0));
        jTFMarca3.setText("" + jTResultados.getModel().getValueAt(selectedRow, 1));
        jTFChasis3.setText("" + jTResultados.getModel().getValueAt(selectedRow, 2));
        jCBTipo3.setSelectedItem("" + jTResultados.getModel().getValueAt(selectedRow, 3));
        jTFAsientos3.setText("" + jTResultados.getModel().getValueAt(selectedRow, 4));
        jTFCapacidad3.setText("" + jTResultados.getModel().getValueAt(selectedRow, 5));
        jCBRuta3.setSelectedItem("" + jTResultados.getModel().getValueAt(selectedRow, 6));


        jTPBus.setSelectedIndex(2);
    }//GEN-LAST:event_jTResultadosMouseClicked

    private void jBConsultar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsultar1ActionPerformed
        LinkedList consulta = new LinkedList();

        try {
            int capacidad = 0;
            try {
                capacidad = Integer.parseInt(jTFCapacidad2.getText());
            } catch (Exception e) {
                capacidad = 0;
            }
            String ruta = jCBRuta2.getSelectedItem().toString();
            
            consulta = controladorBus.consultar(
                    jTFPlaca2.getText(),
                    jCBTipo2.getSelectedItem().toString(),
                    capacidad,
                    ruta);

            Object[][] s = new Object[consulta.size()][7];
            for (int i = 0; i < consulta.size(); i++) {
                Buses bus = (Buses) consulta.get(i);
                if (bus.getPlaca() != null) {
                    s[i][0] = bus.getPlaca();
                    s[i][1] = bus.getMarca();
                    s[i][2] = bus.getNroChasis();
                    s[i][3] = bus.getTipo();
                    s[i][4] = bus.getNroAsientos();
                    s[i][5] = bus.getCapacidad();
                    s[i][6] = bus.getRuta();

                } else {
                    s = null;
                }
            }
            TableModel myModel = new DefaultTableModel(s, new String[]{
                        "Placa", "Marca", "Chasis",
                        "Tipo", "Nro. Asientos", "Capacidad", "Ruta"}) {

                boolean[] canEdit = new boolean[]{false, false, false, false, false, false, false};

                @Override
                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit[columnIndex];
                }
            };
            ///remover filas
            jTResultados.setModel(myModel);
            jTResultados.setRowSorter(new TableRowSorter(myModel));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jBConsultar1ActionPerformed

    private void jBModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarActionPerformed
        int editar = -1;

        try {

            Rutas r = controladorRuta.consultar(jCBRuta3.getSelectedItem().toString());
            editar = controladorBus.modificar(
                    jTFPlaca3.getText(),
                    jTFMarca3.getText(),
                    jTFChasis3.getText(),
                    jCBTipo3.getSelectedItem().toString(),
                    Integer.parseInt(jTFAsientos3.getText()),
                    Integer.parseInt(jTFCapacidad3.getText()),
                    r);


        } catch (Exception e) {
            System.out.print(e);
        }
        if (editar == -1) {
            JOptionPane.showMessageDialog(this, "No su pudo modificar", "Error Base Datos", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "modificado correctamente", "Base Datos", JOptionPane.INFORMATION_MESSAGE);
            limpiarCamposConsultar();
            jTResultados.removeAll();
            jTFPlaca2.setText(jTFPlaca3.getText());
            jBConsultar1.doClick();
            jTPBus.setSelectedIndex(1);
            limpiarCamposModificar();
        }
    }//GEN-LAST:event_jBModificarActionPerformed
    public void limpiarCamposCrear() {
        jTFPlaca1.setText("");
        jTFMarca1.setText("");
        jTFChasis1.setText("");
        jTFAsientos1.setText("");
        jTFCapacidad1.setText("");
        jCBTipo1.setSelectedIndex(0);
        jCBRuta1.setSelectedIndex(0);

    }

    public void limpiarCamposModificar() {
        jTFPlaca3.setText("");
        jTFMarca3.setText("");
        jTFChasis3.setText("");
        jTFAsientos3.setText("");
        jTFCapacidad3.setText("");
        jCBTipo3.setSelectedIndex(0);
        jCBRuta3.setSelectedIndex(0);

    }

    public void limpiarCamposConsultar() {
        jTFPlaca2.setText("");
        jTFCapacidad2.setText("");
        jCBTipo2.setSelectedIndex(0);
        jCBRuta2.setSelectedIndex(0);
    }
    private void jCBRuta1PopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jCBRuta1PopupMenuWillBecomeVisible
        jCBRuta1.setModel(
                new javax.swing.DefaultComboBoxModel(controladorRuta.listar()));
    }//GEN-LAST:event_jCBRuta1PopupMenuWillBecomeVisible

    private void jCBRuta2PopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jCBRuta2PopupMenuWillBecomeVisible
        jCBRuta2.setModel(
                new javax.swing.DefaultComboBoxModel(controladorRuta.listar()));
    }//GEN-LAST:event_jCBRuta2PopupMenuWillBecomeVisible

    private void jCBRuta3PopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jCBRuta3PopupMenuWillBecomeVisible
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBRuta3PopupMenuWillBecomeVisible

    private void jCBRuta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBRuta3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBRuta3ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBConsultar1;
    private javax.swing.JButton jBCrear1;
    private javax.swing.JButton jBLimpiar1;
    private javax.swing.JButton jBLimpiarConsultar;
    private javax.swing.JButton jBModificar;
    private javax.swing.JComboBox jCBRuta1;
    private javax.swing.JComboBox jCBRuta2;
    private javax.swing.JComboBox jCBRuta3;
    private javax.swing.JComboBox jCBTipo1;
    private javax.swing.JComboBox jCBTipo2;
    private javax.swing.JComboBox jCBTipo3;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFAsientos1;
    private javax.swing.JTextField jTFAsientos3;
    private javax.swing.JTextField jTFCapacidad1;
    private javax.swing.JTextField jTFCapacidad2;
    private javax.swing.JTextField jTFCapacidad3;
    private javax.swing.JTextField jTFChasis1;
    private javax.swing.JTextField jTFChasis3;
    private javax.swing.JTextField jTFMarca1;
    private javax.swing.JTextField jTFMarca3;
    private javax.swing.JTextField jTFPlaca1;
    private javax.swing.JTextField jTFPlaca2;
    private javax.swing.JTextField jTFPlaca3;
    private javax.swing.JTabbedPane jTPBus;
    private javax.swing.JTable jTResultados;
    // End of variables declaration//GEN-END:variables
}
