/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.LinkedList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Juan
 */
public class JPEmpleado extends javax.swing.JPanel {

    /**
     * Creates new form JPEmpleado
     */
    public JPEmpleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTPEmpleado = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTFTelefono1 = new javax.swing.JTextField();
        jTFId1 = new javax.swing.JTextField();
        jTFDireccion1 = new javax.swing.JTextField();
        jBLimpiar1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jTFApellido1 = new javax.swing.JTextField();
        jTFNombre1 = new javax.swing.JTextField();
        jTFEmail1 = new javax.swing.JTextField();
        jCBGenero1 = new javax.swing.JComboBox();
        jLabel28 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTFSalario1 = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 2), new java.awt.Dimension(0, 2), new java.awt.Dimension(32767, 2));
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jCBEstaciones1 = new javax.swing.JComboBox();
        jBCrearAuxiliar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTFHoraEntrada1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTHoraSalida1 = new javax.swing.JTextField();
        jBCrearConductor = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jBCrearDirectorEstacion = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jBCrearDirectorOperativo = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jBLimpiarConsultar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTResultados = new javax.swing.JTable();
        jLabel24 = new javax.swing.JLabel();
        jTFId2 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jTFNombre2 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jTFApellido2 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jCBGenero2 = new javax.swing.JComboBox();
        jLabel30 = new javax.swing.JLabel();
        jTFEmail2 = new javax.swing.JTextField();
        jBConsultar1 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        jLabel34 = new javax.swing.JLabel();
        jTFNombre4 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jBModificar = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jTFId3 = new javax.swing.JTextField();
        jTFNombre3 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTFApellido3 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jCBGenero3 = new javax.swing.JComboBox();
        jTFTelefono3 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTFDireccion3 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jTFEmail3 = new javax.swing.JTextField();
        jPFPassword3 = new javax.swing.JPasswordField();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Empleado"));

        jPanel7.setLayout(null);

        jPanel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.setLayout(null);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Dirección");
        jPanel8.add(jLabel11);
        jLabel11.setBounds(10, 160, 70, 30);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Identificación");
        jPanel8.add(jLabel12);
        jLabel12.setBounds(10, 10, 80, 30);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Nombres");
        jPanel8.add(jLabel13);
        jLabel13.setBounds(-20, 50, 120, 30);

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Genero");
        jPanel8.add(jLabel14);
        jLabel14.setBounds(0, 250, 80, 40);

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Telefono");
        jPanel8.add(jLabel15);
        jLabel15.setBounds(0, 120, 80, 40);
        jPanel8.add(jTFTelefono1);
        jTFTelefono1.setBounds(100, 130, 130, 30);
        jPanel8.add(jTFId1);
        jTFId1.setBounds(100, 10, 130, 30);
        jPanel8.add(jTFDireccion1);
        jTFDireccion1.setBounds(100, 170, 130, 30);

        jBLimpiar1.setText("Limpiar");
        jBLimpiar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiar1ActionPerformed(evt);
            }
        });
        jPanel8.add(jBLimpiar1);
        jBLimpiar1.setBounds(420, 410, 70, 23);

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Apellidos");
        jPanel8.add(jLabel16);
        jLabel16.setBounds(0, 80, 80, 30);
        jPanel8.add(jTFApellido1);
        jTFApellido1.setBounds(100, 90, 130, 30);
        jPanel8.add(jTFNombre1);
        jTFNombre1.setBounds(100, 50, 130, 30);
        jPanel8.add(jTFEmail1);
        jTFEmail1.setBounds(100, 210, 130, 30);

        jCBGenero1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Femenino" }));
        jPanel8.add(jCBGenero1);
        jCBGenero1.setBounds(100, 260, 130, 20);

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Email");
        jPanel8.add(jLabel28);
        jLabel28.setBounds(10, 210, 60, 30);

        jLabel1.setText("Salario");
        jPanel8.add(jLabel1);
        jLabel1.setBounds(30, 300, 34, 14);

        jTFSalario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFSalario1ActionPerformed(evt);
            }
        });
        jPanel8.add(jTFSalario1);
        jTFSalario1.setBounds(100, 290, 130, 30);
        jPanel8.add(filler1);
        filler1.setBounds(380, 0, 0, 300);

        jLabel2.setText("Tipo");
        jPanel8.add(jLabel2);
        jLabel2.setBounds(30, 340, 34, 14);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Auxiliar", "Conductor", "Director Estacion", "Director Operativo", "" }));
        jPanel8.add(jComboBox1);
        jComboBox1.setBounds(100, 340, 130, 20);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Auxiliar"));

        jLabel3.setText("Estacion");

        jBCrearAuxiliar.setText("Crear");
        jBCrearAuxiliar.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(jCBEstaciones1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBCrearAuxiliar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jCBEstaciones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jBCrearAuxiliar)
                .addContainerGap())
        );

        jPanel8.add(jPanel1);
        jPanel1.setBounds(250, 10, 240, 90);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Conductor"));

        jLabel4.setText("Hora Entrada");

        jLabel5.setText("Hora Salida");

        jBCrearConductor.setText("Crear");
        jBCrearConductor.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFHoraEntrada1, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                            .addComponent(jTHoraSalida1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBCrearConductor)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFHoraEntrada1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTHoraSalida1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jBCrearConductor)
                .addContainerGap())
        );

        jPanel8.add(jPanel2);
        jPanel2.setBounds(250, 100, 240, 120);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Director de Estacion"));

        jBCrearDirectorEstacion.setText("Crear");
        jBCrearDirectorEstacion.setEnabled(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(159, Short.MAX_VALUE)
                .addComponent(jBCrearDirectorEstacion)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBCrearDirectorEstacion)
                .addContainerGap())
        );

        jPanel8.add(jPanel5);
        jPanel5.setBounds(250, 230, 240, 70);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Director Operativo"));

        jBCrearDirectorOperativo.setText("Crear");
        jBCrearDirectorOperativo.setEnabled(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(159, Short.MAX_VALUE)
                .addComponent(jBCrearDirectorOperativo)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBCrearDirectorOperativo)
                .addContainerGap())
        );

        jPanel8.add(jPanel6);
        jPanel6.setBounds(250, 320, 240, 70);

        jPanel7.add(jPanel8);
        jPanel8.setBounds(0, 0, 510, 450);

        jTPEmpleado.addTab("Crear", jPanel7);

        jPanel3.setLayout(null);

        jPanel9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel9.setLayout(null);

        jBLimpiarConsultar.setText("Limpiar");
        jBLimpiarConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarConsultarActionPerformed(evt);
            }
        });
        jPanel9.add(jBLimpiarConsultar);
        jBLimpiarConsultar.setBounds(310, 180, 90, 23);

        jTResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Nombre", "Apellidos", "Telefono", "Direccion", "Genero", "Email", "Salario", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTResultados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTResultadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTResultados);

        jPanel9.add(jScrollPane1);
        jScrollPane1.setBounds(10, 220, 490, 110);

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Identificación");
        jPanel9.add(jLabel24);
        jLabel24.setBounds(10, 10, 80, 30);
        jPanel9.add(jTFId2);
        jTFId2.setBounds(100, 10, 130, 30);

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Nombres");
        jPanel9.add(jLabel25);
        jLabel25.setBounds(-20, 50, 120, 30);
        jPanel9.add(jTFNombre2);
        jTFNombre2.setBounds(350, 50, 130, 30);

        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Apellidos");
        jPanel9.add(jLabel26);
        jLabel26.setBounds(0, 90, 80, 30);
        jPanel9.add(jTFApellido2);
        jTFApellido2.setBounds(100, 90, 130, 30);

        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Genero");
        jPanel9.add(jLabel29);
        jLabel29.setBounds(0, 120, 80, 40);

        jCBGenero2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Masculino", "Femenino" }));
        jPanel9.add(jCBGenero2);
        jCBGenero2.setBounds(100, 130, 130, 20);

        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Email");
        jPanel9.add(jLabel30);
        jLabel30.setBounds(-10, 160, 90, 30);
        jPanel9.add(jTFEmail2);
        jTFEmail2.setBounds(100, 160, 130, 30);

        jBConsultar1.setText("Consultar");
        jBConsultar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsultar1ActionPerformed(evt);
            }
        });
        jPanel9.add(jBConsultar1);
        jBConsultar1.setBounds(400, 180, 90, 23);

        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("Salario");
        jPanel9.add(jLabel33);
        jLabel33.setBounds(260, 40, 80, 40);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Auxiliar", "Conductor", "Director Estacion", "Director Operativo", "" }));
        jPanel9.add(jComboBox2);
        jComboBox2.setBounds(100, 340, 130, 20);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Auxiliar", "Conductor", "Director Estacion", "Director Operativo", "" }));
        jPanel9.add(jComboBox3);
        jComboBox3.setBounds(100, 340, 130, 60);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Auxiliar", "Conductor", "Director de Estacion", "Director Operativo" }));
        jPanel9.add(jComboBox4);
        jComboBox4.setBounds(350, 20, 130, 20);

        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("Tipo");
        jPanel9.add(jLabel34);
        jLabel34.setBounds(250, 10, 80, 40);
        jPanel9.add(jTFNombre4);
        jTFNombre4.setBounds(100, 50, 130, 30);

        jPanel3.add(jPanel9);
        jPanel9.setBounds(0, 0, 590, 340);

        jTPEmpleado.addTab("Consultar", jPanel3);

        jPanel4.setLayout(null);

        jPanel10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel10.setLayout(null);

        jBModificar.setText("Modificar");
        jBModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarActionPerformed(evt);
            }
        });
        jPanel10.add(jBModificar);
        jBModificar.setBounds(250, 290, 110, 23);

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Identificación");
        jPanel10.add(jLabel17);
        jLabel17.setBounds(10, 10, 80, 30);

        jTFId3.setEditable(false);
        jPanel10.add(jTFId3);
        jTFId3.setBounds(100, 10, 260, 30);
        jPanel10.add(jTFNombre3);
        jTFNombre3.setBounds(100, 50, 260, 30);

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Nombres");
        jPanel10.add(jLabel18);
        jLabel18.setBounds(-20, 50, 120, 30);

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Apellidos");
        jPanel10.add(jLabel19);
        jLabel19.setBounds(0, 90, 80, 30);
        jPanel10.add(jTFApellido3);
        jTFApellido3.setBounds(100, 90, 260, 30);

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Genero");
        jPanel10.add(jLabel20);
        jLabel20.setBounds(0, 120, 80, 40);

        jCBGenero3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Femenino" }));
        jPanel10.add(jCBGenero3);
        jCBGenero3.setBounds(100, 130, 80, 20);
        jPanel10.add(jTFTelefono3);
        jTFTelefono3.setBounds(280, 130, 80, 30);

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Telefono");
        jPanel10.add(jLabel21);
        jLabel21.setBounds(210, 120, 80, 40);

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Dirección");
        jPanel10.add(jLabel22);
        jLabel22.setBounds(10, 170, 70, 30);
        jPanel10.add(jTFDireccion3);
        jTFDireccion3.setBounds(100, 170, 260, 30);

        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Contraseña");
        jPanel10.add(jLabel31);
        jLabel31.setBounds(0, 250, 90, 30);

        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("Email");
        jPanel10.add(jLabel32);
        jLabel32.setBounds(0, 210, 90, 30);
        jPanel10.add(jTFEmail3);
        jTFEmail3.setBounds(100, 210, 260, 30);
        jPanel10.add(jPFPassword3);
        jPFPassword3.setBounds(100, 250, 260, 30);

        jPanel4.add(jPanel10);
        jPanel10.setBounds(0, 10, 510, 440);

        jTPEmpleado.addTab("Modificar", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTPEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTPEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBLimpiar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiar1ActionPerformed
//        limpiarCamposCrear();
    }//GEN-LAST:event_jBLimpiar1ActionPerformed

    private void jBLimpiarConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarConsultarActionPerformed
//        limpiarCamposConsultar();
    }//GEN-LAST:event_jBLimpiarConsultarActionPerformed

    private void jTResultadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTResultadosMouseClicked

//        String id;
//
//        int selectedRow = jTResultados.getSelectedRow();
//        System.out.println(selectedRow);
//        id = jTResultados.getModel().getValueAt(selectedRow, 0).toString();
//        Pasajeros p = controladorPasajero.consultar(id);
//        jPFPassword3.setText(p.getPassword());
//
//        jTFId3.setText("" + jTResultados.getModel().getValueAt(selectedRow, 0));
//        jTFNombre3.setText("" + jTResultados.getModel().getValueAt(selectedRow, 1));
//        jTFApellido3.setText("" + jTResultados.getModel().getValueAt(selectedRow, 2));
//        jTFTelefono3.setText("" + jTResultados.getModel().getValueAt(selectedRow, 3));
//        jTFDireccion3.setText("" + jTResultados.getModel().getValueAt(selectedRow, 4));
//        jCBGenero3.setSelectedItem("" + jTResultados.getModel().getValueAt(selectedRow, 5));
//        jTFEmail3.setText("" + jTResultados.getModel().getValueAt(selectedRow, 6));
//
//        jTPEmpleado.setSelectedIndex(2);
    }//GEN-LAST:event_jTResultadosMouseClicked

    private void jBConsultar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsultar1ActionPerformed
        LinkedList consulta = new LinkedList();

       // try {
//            consulta = controladorPasajero.consultar(
//                    jTFId2.getText(),
//                    jTFNombre2.getText(),
//                    jTFApellido2.getText(),
//                    jCBGenero2.getSelectedItem().toString(),
//                    jTFEmail2.getText());
//
//            Object[][] s = new Object[consulta.size()][7];
//            for (int i = 0; i < consulta.size(); i++) {
//                Pasajeros pasajero = (Pasajeros) consulta.get(i);
//                if (pasajero.getNombres() != null) {
//                    s[i][0] = pasajero.getIdentificacion();
//                    s[i][1] = pasajero.getNombres();
//                    s[i][2] = pasajero.getApellidos();
//                    s[i][3] = pasajero.getTelefono();
//                    s[i][4] = pasajero.getDireccion();
//                    s[i][5] = pasajero.getGenero();
//                    s[i][6] = pasajero.getEmail();

//                } else {
//                    s = null;
//                }
        //    }
//            TableModel myModel = new DefaultTableModel(s, new String[]{"Id", "Nombres", "Apellidos",
//                        "Telefono", "Direccion", "Genero", "Email"}) {
//
//                boolean[] canEdit = new boolean[]{false, false, false, false, false, false, false};
//
//                @Override
//                public boolean isCellEditable(int rowIndex, int columnIndex) {
//                    return canEdit[columnIndex];
//                }
//            };
//            ///remover filas
//            jTResultados.setModel(myModel);
//            jTResultados.setRowSorter(new TableRowSorter(myModel));
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
    }//GEN-LAST:event_jBConsultar1ActionPerformed

    private void jBModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarActionPerformed
//        int editar = -1;
//
//        try {
//            editar = controladorPasajero.modificar(
//                    jTFId3.getText(),
//                    jTFNombre3.getText(),
//                    jTFApellido3.getText(),
//                    jTFTelefono3.getText(),
//                    jTFDireccion3.getText(),
//                    jCBGenero3.getSelectedItem().toString(),
//                    jTFEmail3.getText(),
//                    jPFPassword3.getText());
//
//
//        } catch (Exception e) {
//            System.out.print(e);
//        }
//        if (editar == -1) {
//            JOptionPane.showMessageDialog(this, "No su pudo modificar el pasajero", "Error Base Datos", JOptionPane.ERROR_MESSAGE);
//        } else {
//            JOptionPane.showMessageDialog(this, "modificado correctamente", "Base Datos", JOptionPane.INFORMATION_MESSAGE);
//            limpiarCamposConsultar();
//            jTFId2.setText(jTFId3.getText());
//            jBConsultar1.doClick();
//            jTPEmpleado.setSelectedIndex(1);
//            limpiarCamposModificar();
//        }
    }//GEN-LAST:event_jBModificarActionPerformed

    private void jTFSalario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFSalario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFSalario1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jBConsultar1;
    private javax.swing.JButton jBCrearAuxiliar;
    private javax.swing.JButton jBCrearConductor;
    private javax.swing.JButton jBCrearDirectorEstacion;
    private javax.swing.JButton jBCrearDirectorOperativo;
    private javax.swing.JButton jBLimpiar1;
    private javax.swing.JButton jBLimpiarConsultar;
    private javax.swing.JButton jBModificar;
    private javax.swing.JComboBox jCBEstaciones1;
    private javax.swing.JComboBox jCBGenero1;
    private javax.swing.JComboBox jCBGenero2;
    private javax.swing.JComboBox jCBGenero3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPFPassword3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFApellido1;
    private javax.swing.JTextField jTFApellido2;
    private javax.swing.JTextField jTFApellido3;
    private javax.swing.JTextField jTFDireccion1;
    private javax.swing.JTextField jTFDireccion3;
    private javax.swing.JTextField jTFEmail1;
    private javax.swing.JTextField jTFEmail2;
    private javax.swing.JTextField jTFEmail3;
    private javax.swing.JTextField jTFHoraEntrada1;
    private javax.swing.JTextField jTFId1;
    private javax.swing.JTextField jTFId2;
    private javax.swing.JTextField jTFId3;
    private javax.swing.JTextField jTFNombre1;
    private javax.swing.JTextField jTFNombre2;
    private javax.swing.JTextField jTFNombre3;
    private javax.swing.JTextField jTFNombre4;
    private javax.swing.JTextField jTFSalario1;
    private javax.swing.JTextField jTFTelefono1;
    private javax.swing.JTextField jTFTelefono3;
    private javax.swing.JTextField jTHoraSalida1;
    private javax.swing.JTabbedPane jTPEmpleado;
    private javax.swing.JTable jTResultados;
    // End of variables declaration//GEN-END:variables
}
