/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import controladores.ControladorDirectorEstacion;
import controladores.ControladorEmpleado;
import controladores.ControladorEstacion;
import entidades.DirectoresEstacion;
import entidades.Empleados;
import entidades.Estaciones;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Juan
 */
public class JPEstacion extends javax.swing.JPanel {

    /**
     * Creates new form JPEstacion
     */
    ControladorEstacion controladorEstacion;
    ControladorDirectorEstacion controladorDirEstacion;
    ControladorEmpleado controladorEmpleados;
    
    public JPEstacion() {
        initComponents();
        controladorEstacion=new ControladorEstacion();
        controladorDirEstacion= new ControladorDirectorEstacion();
        controladorEmpleados= new ControladorEmpleado();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTPEstacion = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTFNombre1 = new javax.swing.JTextField();
        jBLimpiar1 = new javax.swing.JButton();
        jTFUbicacion1 = new javax.swing.JTextField();
        jBCrear1 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jCBDirector1 = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jBLimpiarConsultar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTResultados = new javax.swing.JTable();
        jBConsultar1 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jTFNombre2 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jTFUbicacion2 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jCBDirector2 = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jBModificar = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jTFNombre3 = new javax.swing.JTextField();
        jTFUbicacion3 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jCBDirector3 = new javax.swing.JComboBox();
        jLabel35 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Estacion"));

        jPanel7.setLayout(null);

        jPanel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.setLayout(null);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Nombre");
        jPanel8.add(jLabel12);
        jLabel12.setBounds(0, 10, 80, 30);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Ubicacion");
        jPanel8.add(jLabel13);
        jLabel13.setBounds(-20, 50, 120, 30);
        jPanel8.add(jTFNombre1);
        jTFNombre1.setBounds(100, 10, 180, 30);

        jBLimpiar1.setText("Limpiar");
        jBLimpiar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiar1ActionPerformed(evt);
            }
        });
        jPanel8.add(jBLimpiar1);
        jBLimpiar1.setBounds(120, 160, 70, 23);
        jPanel8.add(jTFUbicacion1);
        jTFUbicacion1.setBounds(100, 50, 180, 30);

        jBCrear1.setText("Crear");
        jBCrear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCrear1ActionPerformed(evt);
            }
        });
        jPanel8.add(jBCrear1);
        jBCrear1.setBounds(220, 160, 59, 23);

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Director");
        jPanel8.add(jLabel28);
        jLabel28.setBounds(-10, 100, 90, 30);

        jCBDirector1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));
        jCBDirector1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jCBDirector1PopupMenuWillBecomeVisible(evt);
            }
        });
        jPanel8.add(jCBDirector1);
        jCBDirector1.setBounds(100, 100, 180, 30);

        jPanel7.add(jPanel8);
        jPanel8.setBounds(0, 0, 380, 310);

        jTPEstacion.addTab("Crear", jPanel7);

        jPanel3.setLayout(null);

        jPanel9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel9.setLayout(null);

        jBLimpiarConsultar.setText("Limpiar");
        jBLimpiarConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarConsultarActionPerformed(evt);
            }
        });
        jPanel9.add(jBLimpiarConsultar);
        jBLimpiarConsultar.setBounds(290, 100, 90, 23);

        jTResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Ubicacion", "Director"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTResultados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTResultadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTResultados);

        jPanel9.add(jScrollPane1);
        jScrollPane1.setBounds(10, 210, 370, 80);

        jBConsultar1.setText("Consultar");
        jBConsultar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsultar1ActionPerformed(evt);
            }
        });
        jPanel9.add(jBConsultar1);
        jBConsultar1.setBounds(290, 140, 90, 23);

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Nombre");
        jPanel9.add(jLabel23);
        jLabel23.setBounds(0, 10, 80, 30);

        jTFNombre2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNombre2ActionPerformed(evt);
            }
        });
        jPanel9.add(jTFNombre2);
        jTFNombre2.setBounds(80, 10, 180, 30);

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Ubicacion");
        jPanel9.add(jLabel27);
        jLabel27.setBounds(0, 40, 80, 40);
        jPanel9.add(jTFUbicacion2);
        jTFUbicacion2.setBounds(80, 50, 180, 30);

        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("Director");
        jPanel9.add(jLabel34);
        jLabel34.setBounds(-10, 100, 90, 30);

        jCBDirector2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));
        jCBDirector2.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jCBDirector2PopupMenuWillBecomeVisible(evt);
            }
        });
        jPanel9.add(jCBDirector2);
        jCBDirector2.setBounds(80, 100, 180, 30);

        jPanel3.add(jPanel9);
        jPanel9.setBounds(0, 0, 590, 340);

        jTPEstacion.addTab("Consultar", jPanel3);

        jPanel4.setLayout(null);

        jPanel10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel10.setLayout(null);

        jBModificar.setText("Modificar");
        jBModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarActionPerformed(evt);
            }
        });
        jPanel10.add(jBModificar);
        jBModificar.setBounds(170, 270, 110, 23);

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Nombre");
        jPanel10.add(jLabel24);
        jLabel24.setBounds(-10, 10, 80, 30);

        jTFNombre3.setEditable(false);
        jPanel10.add(jTFNombre3);
        jTFNombre3.setBounds(100, 10, 180, 30);
        jPanel10.add(jTFUbicacion3);
        jTFUbicacion3.setBounds(100, 50, 180, 30);

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Ubicacion");
        jPanel10.add(jLabel25);
        jLabel25.setBounds(-20, 50, 120, 30);

        jCBDirector3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cargar" }));
        jCBDirector3.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jCBDirector3PopupMenuWillBecomeVisible(evt);
            }
        });
        jCBDirector3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBDirector3ActionPerformed(evt);
            }
        });
        jPanel10.add(jCBDirector3);
        jCBDirector3.setBounds(100, 90, 180, 30);

        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("Director");
        jPanel10.add(jLabel35);
        jLabel35.setBounds(0, 90, 90, 30);

        jPanel4.add(jPanel10);
        jPanel10.setBounds(0, 10, 450, 320);

        jTPEstacion.addTab("Modificar", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTPEstacion, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTPEstacion, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBLimpiar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiar1ActionPerformed
        limpiarCamposCrear();
    }//GEN-LAST:event_jBLimpiar1ActionPerformed

   public void  limpiarCamposCrear(){
       jTFNombre1.setText("");
       jTFUbicacion1.setText("");
       jCBDirector1.setSelectedIndex(0);
   }
   
   public void  limpiarCamposConsultar(){
       jTFNombre2.setText("");
       jTFUbicacion2.setText("");
       jCBDirector2.setSelectedIndex(0);
   }
    public void  limpiarCamposModificar(){
       jTFNombre3.setText("");
       jTFUbicacion3.setText("");
       jCBDirector3.setSelectedIndex(0);
   }
   
    private void jBCrear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCrear1ActionPerformed

        int guardar = -1;
        try {

            String nombre = jTFNombre1.getText();
            String ubicacion = jTFUbicacion1.getText();        
            String director = jCBDirector1.getSelectedItem().toString();          
          
            DirectoresEstacion dE = controladorDirEstacion.consultar(director);
            guardar = controladorEstacion.insertar(nombre, ubicacion, dE);

        } catch (Exception e) {
        }
        if (guardar == -1) {
            JOptionPane.showMessageDialog(this, "No se pudo crear ", "Error Base Datos", JOptionPane.ERROR_MESSAGE);
        } else {

            if (guardar == 1) {

                JOptionPane.showMessageDialog(this, "Ya existe la Estacion ", "Error", ERROR);


            } else {
                JOptionPane.showMessageDialog(this, "Estacion Creada correctamente", "Sistema", JOptionPane.INFORMATION_MESSAGE);

                limpiarCamposConsultar();
                jTFNombre2.setText(jTFNombre1.getText());
                jBConsultar1.doClick();
                jTPEstacion.setSelectedIndex(1);
                limpiarCamposCrear();
            }
        }
    }//GEN-LAST:event_jBCrear1ActionPerformed

    private void jCBDirector1PopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jCBDirector1PopupMenuWillBecomeVisible
        jCBDirector1.setModel(
                new javax.swing.DefaultComboBoxModel(controladorDirEstacion.listar()));
    }//GEN-LAST:event_jCBDirector1PopupMenuWillBecomeVisible

    private void jBLimpiarConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarConsultarActionPerformed
        limpiarCamposConsultar();
    }//GEN-LAST:event_jBLimpiarConsultarActionPerformed

    private void jTResultadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTResultadosMouseClicked

        int selectedRow = jTResultados.getSelectedRow();
        jCBDirector3.setModel(
                new javax.swing.DefaultComboBoxModel(controladorDirEstacion.listar()));
        jTFNombre3.setText("" + jTResultados.getModel().getValueAt(selectedRow, 0));
        jTFUbicacion3.setText("" + jTResultados.getModel().getValueAt(selectedRow, 1));
        jCBDirector3.setSelectedItem("" + jTResultados.getModel().getValueAt(selectedRow, 2));


        jTPEstacion.setSelectedIndex(2);
    }//GEN-LAST:event_jTResultadosMouseClicked

    private void jBConsultar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsultar1ActionPerformed
        LinkedList consulta = new LinkedList();

        try {
           
            
            String director = jCBDirector2.getSelectedItem().toString();

            consulta = controladorEstacion.consultar(
                    jTFNombre2.getText(),
                    jTFUbicacion2.getText(),
                    director);

            Object[][] s = new Object[consulta.size()][5];
            for (int i = 0; i < consulta.size(); i++) {
                Estaciones e = (Estaciones) consulta.get(i);
                DirectoresEstacion directorEst=controladorDirEstacion.consultar(e.getDirector());
                Empleados empl=controladorEmpleados.consultar(directorEst.getIdentificacion());
                if (e.getNombre() != null) {
                    s[i][0] = e.getNombre();
                    s[i][1] = e.getUbicacion();
                    s[i][2] = e.getDirector();
                    s[i][3] = empl.getNombres();
                    s[i][4] = empl.getApellidos();
                   

                } else {
                    s = null;
                }
            }
            TableModel myModel = new DefaultTableModel(s, new String[]{
                        "Estacion", "Ubicacion", "Id-Director",
                        "Nombre Dir", "Apellido Dir"}) {

                boolean[] canEdit = new boolean[]{false, false, false, false, false};

                @Override
                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit[columnIndex];
                }
            };
            ///remover filas
            jTResultados.setModel(myModel);
            jTResultados.setRowSorter(new TableRowSorter(myModel));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jBConsultar1ActionPerformed

    private void jCBDirector2PopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jCBDirector2PopupMenuWillBecomeVisible
        jCBDirector2.setModel(
                new javax.swing.DefaultComboBoxModel(controladorDirEstacion.listar()));
    }//GEN-LAST:event_jCBDirector2PopupMenuWillBecomeVisible

    private void jBModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarActionPerformed
        int editar = -1;

        try {

            DirectoresEstacion director =controladorDirEstacion.consultar(jCBDirector3.getSelectedItem().toString());
            editar = controladorEstacion.modificar(
                    jTFNombre3.getText(),
                    jTFUbicacion3.getText(),                  
                    director);


        } catch (Exception e) {
            System.out.print(e);
        }
        if (editar == -1) {
            JOptionPane.showMessageDialog(this, "No su pudo modificar", "Error Base Datos", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "modificado correctamente", "Base Datos", JOptionPane.INFORMATION_MESSAGE);
            limpiarCamposConsultar();
            jTResultados.removeAll();
            jTFNombre2.setText(jTFNombre3.getText());
            jBConsultar1.doClick();
            jTPEstacion.setSelectedIndex(1);
            limpiarCamposModificar();
        }
    }//GEN-LAST:event_jBModificarActionPerformed

    private void jCBDirector3PopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jCBDirector3PopupMenuWillBecomeVisible
        // TODO add your handling code here:
         jCBDirector1.setModel(
                new javax.swing.DefaultComboBoxModel(controladorDirEstacion.listar()));
   
    }//GEN-LAST:event_jCBDirector3PopupMenuWillBecomeVisible

    private void jCBDirector3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBDirector3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBDirector3ActionPerformed

    private void jTFNombre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNombre2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNombre2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBConsultar1;
    private javax.swing.JButton jBCrear1;
    private javax.swing.JButton jBLimpiar1;
    private javax.swing.JButton jBLimpiarConsultar;
    private javax.swing.JButton jBModificar;
    private javax.swing.JComboBox jCBDirector1;
    private javax.swing.JComboBox jCBDirector2;
    private javax.swing.JComboBox jCBDirector3;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFNombre1;
    private javax.swing.JTextField jTFNombre2;
    private javax.swing.JTextField jTFNombre3;
    private javax.swing.JTextField jTFUbicacion1;
    private javax.swing.JTextField jTFUbicacion2;
    private javax.swing.JTextField jTFUbicacion3;
    private javax.swing.JTabbedPane jTPEstacion;
    private javax.swing.JTable jTResultados;
    // End of variables declaration//GEN-END:variables
}
