/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import controladores.*;
import entidades.Empleados;
import entidades.Turnos;
import java.sql.Time;
import java.util.LinkedList;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Juan
 */
public class JPProgramarTurnos extends javax.swing.JPanel {

    /**
     * Creates new form JPProgramarTurnos
     */
    ControladorBus controladorBus;
    ControladorTurnos cTurnos;
    ControladorConductor controladorConductor;
    ControladorEmpleado cE;
    
    public JPProgramarTurnos() {
        initComponents();
        controladorBus=new ControladorBus();
        cTurnos=new ControladorTurnos();
        controladorConductor= new ControladorConductor();
        cE=new ControladorEmpleado();
        
         //SPINNERS RESTRINGIR HORA Y MINUTOS
        SpinnerNumberModel modeloSpinnersHE= new SpinnerNumberModel(0, 0, 23, 1);
        SpinnerNumberModel modeloSpinnersHS= new SpinnerNumberModel(0, 0, 23, 1);
        SpinnerNumberModel modeloSpinnersME= new SpinnerNumberModel(0, 0, 59, 1);
        SpinnerNumberModel modeloSpinnersMS= new SpinnerNumberModel(0, 0, 59, 1);
        jSHoraEntrada.setModel(modeloSpinnersHE);
        jSHoraSalida.setModel(modeloSpinnersHS);
        jSMinutosEntrada.setModel(modeloSpinnersME);
        jSMinutosSalida.setModel(modeloSpinnersMS);
        JFormattedTextField tfHE = ((JSpinner.DefaultEditor)jSHoraEntrada.getEditor())
        .getTextField();
        tfHE.setEditable(false);
        //----------------------
         JFormattedTextField tfHS = ((JSpinner.DefaultEditor)jSHoraSalida.getEditor())
        .getTextField();
        tfHS.setEditable(false);
        //----------------------
          JFormattedTextField tfME = ((JSpinner.DefaultEditor)jSMinutosEntrada.getEditor())
        .getTextField();
        tfME.setEditable(false);
        //----------------------
         JFormattedTextField tfMS = ((JSpinner.DefaultEditor)jSMinutosSalida.getEditor())
        .getTextField();
        tfMS.setEditable(false);
        //----------------------
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTPTurnos = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jBLimpiar1 = new javax.swing.JButton();
        jBCrear1 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jCBConductor1 = new javax.swing.JComboBox();
        jCBBus1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSHoraEntrada = new javax.swing.JSpinner();
        jSHoraSalida = new javax.swing.JSpinner();
        jSMinutosSalida = new javax.swing.JSpinner();
        jSMinutosEntrada = new javax.swing.JSpinner();
        jPanel3 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jBLimpiarConsultar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTResultados = new javax.swing.JTable();
        jBConsultar1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jCBBus2 = new javax.swing.JComboBox();
        jCBConductor2 = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jBModificar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSMinutosSalida1 = new javax.swing.JSpinner();
        jSHoraSalida1 = new javax.swing.JSpinner();
        jCBBus3 = new javax.swing.JComboBox();
        jCBConductor3 = new javax.swing.JComboBox();
        jSHoraEntrada1 = new javax.swing.JSpinner();
        jSMinutosEntrada1 = new javax.swing.JSpinner();

        jLabel1.setText("jLabel1");

        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Turnos")));

        jPanel7.setLayout(null);

        jPanel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.setLayout(null);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Conductor");
        jPanel8.add(jLabel11);
        jLabel11.setBounds(20, 10, 60, 30);

        jBLimpiar1.setText("Limpiar");
        jBLimpiar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiar1ActionPerformed(evt);
            }
        });
        jPanel8.add(jBLimpiar1);
        jBLimpiar1.setBounds(120, 220, 70, 23);

        jBCrear1.setText("Crear");
        jBCrear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCrear1ActionPerformed(evt);
            }
        });
        jPanel8.add(jBCrear1);
        jBCrear1.setBounds(230, 220, 59, 23);

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Bus");
        jPanel8.add(jLabel28);
        jLabel28.setBounds(-10, 60, 90, 30);

        jCBConductor1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Troncal", "Alimentador", "Padron" }));
        jCBConductor1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jCBConductor1PopupMenuWillBecomeVisible(evt);
            }
        });
        jPanel8.add(jCBConductor1);
        jCBConductor1.setBounds(110, 10, 180, 30);

        jCBBus1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));
        jCBBus1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jCBBus1PopupMenuWillBecomeVisible(evt);
            }
        });
        jPanel8.add(jCBBus1);
        jCBBus1.setBounds(110, 60, 180, 30);

        jLabel2.setText("Hora Inicio");
        jPanel8.add(jLabel2);
        jLabel2.setBounds(30, 120, 80, 14);

        jLabel3.setText("Hora Fin");
        jPanel8.add(jLabel3);
        jLabel3.setBounds(30, 170, 60, 14);

        jSHoraEntrada.setToolTipText("hora");
        jPanel8.add(jSHoraEntrada);
        jSHoraEntrada.setBounds(120, 120, 29, 20);

        jSHoraSalida.setToolTipText("hora");
        jPanel8.add(jSHoraSalida);
        jSHoraSalida.setBounds(120, 170, 29, 20);

        jSMinutosSalida.setToolTipText("minutos");
        jPanel8.add(jSMinutosSalida);
        jSMinutosSalida.setBounds(180, 170, 29, 20);

        jSMinutosEntrada.setToolTipText("minutos");
        jPanel8.add(jSMinutosEntrada);
        jSMinutosEntrada.setBounds(180, 120, 29, 20);

        jPanel7.add(jPanel8);
        jPanel8.setBounds(0, 0, 370, 310);

        jTPTurnos.addTab("Crear", jPanel7);

        jPanel3.setLayout(null);

        jPanel9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel9.setLayout(null);

        jBLimpiarConsultar.setText("Limpiar");
        jBLimpiarConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarConsultarActionPerformed(evt);
            }
        });
        jPanel9.add(jBLimpiarConsultar);
        jBLimpiarConsultar.setBounds(100, 140, 90, 23);

        jTResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Conductor", "Nombre", "Apellido", "Bus", "hora entrada", "hora salida"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTResultados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTResultadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTResultados);

        jPanel9.add(jScrollPane1);
        jScrollPane1.setBounds(10, 190, 360, 100);

        jBConsultar1.setText("Consultar");
        jBConsultar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsultar1ActionPerformed(evt);
            }
        });
        jPanel9.add(jBConsultar1);
        jBConsultar1.setBounds(200, 140, 90, 23);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Conductor");
        jPanel9.add(jLabel12);
        jLabel12.setBounds(20, 10, 60, 30);

        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Bus");
        jPanel9.add(jLabel31);
        jLabel31.setBounds(-10, 60, 90, 30);

        jCBBus2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));
        jCBBus2.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jCBBus2PopupMenuWillBecomeVisible(evt);
            }
        });
        jPanel9.add(jCBBus2);
        jCBBus2.setBounds(110, 60, 180, 30);

        jCBConductor2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Troncal", "Alimentador", "Padron" }));
        jCBConductor2.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jCBConductor2PopupMenuWillBecomeVisible(evt);
            }
        });
        jPanel9.add(jCBConductor2);
        jCBConductor2.setBounds(110, 10, 180, 30);

        jPanel3.add(jPanel9);
        jPanel9.setBounds(0, 0, 590, 340);

        jTPTurnos.addTab("Consultar", jPanel3);

        jPanel4.setLayout(null);

        jPanel10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel10.setLayout(null);

        jBModificar.setText("Modificar");
        jBModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarActionPerformed(evt);
            }
        });
        jPanel10.add(jBModificar);
        jBModificar.setBounds(180, 250, 110, 23);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Conductor");
        jPanel10.add(jLabel13);
        jLabel13.setBounds(20, 10, 60, 30);

        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("Bus");
        jPanel10.add(jLabel32);
        jLabel32.setBounds(-10, 60, 90, 30);

        jLabel4.setText("Hora Inicio");
        jPanel10.add(jLabel4);
        jLabel4.setBounds(30, 120, 80, 14);

        jLabel5.setText("Hora Fin");
        jPanel10.add(jLabel5);
        jLabel5.setBounds(30, 170, 60, 14);

        jSMinutosSalida1.setToolTipText("minutos");
        jPanel10.add(jSMinutosSalida1);
        jSMinutosSalida1.setBounds(180, 160, 29, 20);

        jSHoraSalida1.setToolTipText("hora");
        jPanel10.add(jSHoraSalida1);
        jSHoraSalida1.setBounds(120, 160, 29, 20);

        jCBBus3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));
        jCBBus3.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jCBBus3PopupMenuWillBecomeVisible(evt);
            }
        });
        jPanel10.add(jCBBus3);
        jCBBus3.setBounds(110, 60, 180, 30);

        jCBConductor3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Troncal", "Alimentador", "Padron" }));
        jCBConductor3.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jCBConductor3PopupMenuWillBecomeVisible(evt);
            }
        });
        jPanel10.add(jCBConductor3);
        jCBConductor3.setBounds(110, 10, 180, 30);

        jSHoraEntrada1.setToolTipText("hora");
        jPanel10.add(jSHoraEntrada1);
        jSHoraEntrada1.setBounds(120, 120, 29, 20);

        jSMinutosEntrada1.setToolTipText("minutos");
        jPanel10.add(jSMinutosEntrada1);
        jSMinutosEntrada1.setBounds(180, 120, 29, 20);

        jPanel4.add(jPanel10);
        jPanel10.setBounds(0, 10, 450, 320);

        jTPTurnos.addTab("Modificar", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTPTurnos, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTPTurnos, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBLimpiar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiar1ActionPerformed
        jCBBus1.setSelectedIndex(0);
        jCBConductor1.setSelectedIndex(0);
        jSHoraEntrada.setValue(0);
        jSHoraSalida.setValue(0);
        jSMinutosEntrada.setValue(0);
        jSMinutosSalida.setValue(0);
    }//GEN-LAST:event_jBLimpiar1ActionPerformed

    private void jBCrear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCrear1ActionPerformed

        int guardar = -1;
        try {

            String conductor =jCBConductor1.getSelectedItem().toString();
            String bus = jCBBus1.getSelectedItem().toString();
          
             int horaSalida=(Integer)jSHoraSalida.getValue();
            int horaEntrada=(Integer)jSHoraEntrada.getValue();
            int minutoSalida=(Integer)jSMinutosSalida.getValue();
            int minutoEntrada=(Integer)jSMinutosEntrada.getValue();
            Time hora_inicio= new Time(horaEntrada, minutoEntrada, 0);
            Time hora_salida= new Time(horaSalida, minutoSalida, 0);
           
            guardar = cTurnos.insertar(conductor, bus, hora_inicio, hora_salida);

        } catch (Exception e) {
        }
        if (guardar == -1) {
            JOptionPane.showMessageDialog(this, "No se pudo crear ", "Error Base Datos", JOptionPane.ERROR_MESSAGE);
        } else {

            if (guardar == 1) {

                JOptionPane.showMessageDialog(this, "Ya existe ", "Error", ERROR);


            } else {
                JOptionPane.showMessageDialog(this, "Turno Creado correctamente", "Sistema", JOptionPane.INFORMATION_MESSAGE);

                jBLimpiarConsultar.doClick();
                jCBConductor2.setSelectedItem(jCBConductor1.getSelectedItem());
                jBConsultar1.doClick();
                jTPTurnos.setSelectedIndex(1);
               jBLimpiar1.doClick();
            }
        }
    }//GEN-LAST:event_jBCrear1ActionPerformed

    private void jCBBus1PopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jCBBus1PopupMenuWillBecomeVisible
        jCBBus1.setModel(
                new javax.swing.DefaultComboBoxModel(controladorBus.listar()));
    }//GEN-LAST:event_jCBBus1PopupMenuWillBecomeVisible

    private void jBLimpiarConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarConsultarActionPerformed
        jCBBus2.setSelectedIndex(0);
        jCBConductor2.setSelectedIndex(0);
    }//GEN-LAST:event_jBLimpiarConsultarActionPerformed

    private void jTResultadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTResultadosMouseClicked

        int selectedRow = jTResultados.getSelectedRow();
        jCBConductor3.setModel(
                new javax.swing.DefaultComboBoxModel(controladorConductor.listar()));
        jCBBus3.setModel(
                new javax.swing.DefaultComboBoxModel(controladorBus.listar()));
        Time h=(Time)jTResultados.getModel().getValueAt(selectedRow, 4);
        Time s=(Time)jTResultados.getModel().getValueAt(selectedRow, 5);
        jSHoraEntrada1.setValue(h.getHours());
        jSHoraSalida1.setValue(s.getHours());
        jSMinutosEntrada1.setValue(h.getMinutes());
         jSMinutosSalida1.setValue(s.getMinutes());
          jCBConductor3.setSelectedItem("" + jTResultados.getModel().getValueAt(selectedRow, 0));
         jCBBus3.setSelectedItem("" + jTResultados.getModel().getValueAt(selectedRow, 3));


        jTPTurnos.setSelectedIndex(2);
    }//GEN-LAST:event_jTResultadosMouseClicked

    private void jBConsultar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsultar1ActionPerformed
        LinkedList consulta = new LinkedList();

        try {
            
       
            consulta = cTurnos.consultar(jCBConductor2.getSelectedItem().toString(),
                    jCBBus2.getSelectedItem().toString()
                   );

            Object[][] s = new Object[consulta.size()][6];
            for (int i = 0; i < consulta.size(); i++) {
                Turnos t = (Turnos) consulta.get(i);
                Empleados e=cE.consultar(t.getTurnosPK().getConductor());
                        if (t.getTurnosPK().getConductor() != null) {
                    s[i][0] = t.getTurnosPK().getConductor();
                    s[i][1] =e.getNombres();
                    s[i][2] = e.getApellidos();
                    s[i][3] = t.getTurnosPK().getBus();
                    s[i][4] = t.getTurnosPK().getHoraInicio();
                    s[i][5] = t.getHoraFin();

                } else {
                    s = null;
                }
            }
            TableModel myModel = new DefaultTableModel(s, new String[]{
                        "Id conductor", "Nombre", "Apellido",
                        "Bus", "Hora inicio", "Hora fin"}) {

                boolean[] canEdit = new boolean[]{false,false, false, false, false, false};

                @Override
                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit[columnIndex];
                }
            };
            ///remover filas
            jTResultados.setModel(myModel);
            jTResultados.setRowSorter(new TableRowSorter(myModel));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jBConsultar1ActionPerformed

    private void jBModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarActionPerformed
        int editar = -1;

        try {
            String conductor =jCBConductor3.getSelectedItem().toString();
            String bus = jCBBus3.getSelectedItem().toString();
          
             int horaSalida=(Integer)jSHoraSalida1.getValue();
            int horaEntrada=(Integer)jSHoraEntrada1.getValue();
            int minutoSalida=(Integer)jSMinutosSalida1.getValue();
            int minutoEntrada=(Integer)jSMinutosEntrada1.getValue();
            Time hora_inicio= new Time(horaEntrada, minutoEntrada, 0);
            Time hora_salida= new Time(horaSalida, minutoSalida, 0);
           
            editar = cTurnos.modificar(conductor, bus, hora_inicio, hora_salida);


        } catch (Exception e) {
            System.out.print(e);
        }
        if (editar == -1) {
            JOptionPane.showMessageDialog(this, "No su pudo modificar", "Error Base Datos", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "modificado correctamente", "Base Datos", JOptionPane.INFORMATION_MESSAGE);
            jBLimpiarConsultar.doClick();
            jTResultados.removeAll();            
            jBConsultar1.doClick();
            jTPTurnos.setSelectedIndex(1);
           
        }
    }//GEN-LAST:event_jBModificarActionPerformed

    private void jCBBus2PopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jCBBus2PopupMenuWillBecomeVisible
        // TODO add your handling code here:
         jCBBus2.setModel(
                new javax.swing.DefaultComboBoxModel(controladorBus.listar()));
  
    }//GEN-LAST:event_jCBBus2PopupMenuWillBecomeVisible

    private void jCBBus3PopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jCBBus3PopupMenuWillBecomeVisible
        // TODO add your handling code here:
         jCBBus3.setModel(
                new javax.swing.DefaultComboBoxModel(controladorBus.listar()));
  
    }//GEN-LAST:event_jCBBus3PopupMenuWillBecomeVisible

    private void jCBConductor1PopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jCBConductor1PopupMenuWillBecomeVisible
        // TODO add your handling code here:
         jCBConductor1.setModel(
                new javax.swing.DefaultComboBoxModel(controladorConductor.listar()));
  
    }//GEN-LAST:event_jCBConductor1PopupMenuWillBecomeVisible

    private void jCBConductor2PopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jCBConductor2PopupMenuWillBecomeVisible
        jCBConductor2.setModel(
                new javax.swing.DefaultComboBoxModel(controladorConductor.listar()));
  // TODO add your handling code here:
    }//GEN-LAST:event_jCBConductor2PopupMenuWillBecomeVisible

    private void jCBConductor3PopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jCBConductor3PopupMenuWillBecomeVisible
        // TODO add your handling code here:
        jCBConductor3.setModel(
                new javax.swing.DefaultComboBoxModel(controladorConductor.listar()));
  
    }//GEN-LAST:event_jCBConductor3PopupMenuWillBecomeVisible

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBConsultar1;
    private javax.swing.JButton jBCrear1;
    private javax.swing.JButton jBLimpiar1;
    private javax.swing.JButton jBLimpiarConsultar;
    private javax.swing.JButton jBModificar;
    private javax.swing.JComboBox jCBBus1;
    private javax.swing.JComboBox jCBBus2;
    private javax.swing.JComboBox jCBBus3;
    private javax.swing.JComboBox jCBConductor1;
    private javax.swing.JComboBox jCBConductor2;
    private javax.swing.JComboBox jCBConductor3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSpinner jSHoraEntrada;
    private javax.swing.JSpinner jSHoraEntrada1;
    private javax.swing.JSpinner jSHoraSalida;
    private javax.swing.JSpinner jSHoraSalida1;
    private javax.swing.JSpinner jSMinutosEntrada;
    private javax.swing.JSpinner jSMinutosEntrada1;
    private javax.swing.JSpinner jSMinutosSalida;
    private javax.swing.JSpinner jSMinutosSalida1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTPTurnos;
    private javax.swing.JTable jTResultados;
    // End of variables declaration//GEN-END:variables
}
