/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author Juan
 */
public class JPReclamo extends javax.swing.JPanel {

    /**
     * Creates new form JPReclamo
     */
    public JPReclamo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTPBus = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTFCod1 = new javax.swing.JTextField();
        jBLimpiar1 = new javax.swing.JButton();
        jBCrear1 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jCBPasajero1 = new javax.swing.JComboBox();
        jCBEstacion1 = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTADescripcion1 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jBLimpiarConsultar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTResultados = new javax.swing.JTable();
        jBConsultar1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jTFCod2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jCBPasajero2 = new javax.swing.JComboBox();
        jLabel31 = new javax.swing.JLabel();
        jCBEstacion2 = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jBModificar = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jTFPlaca3 = new javax.swing.JTextField();
        jTFMarca3 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jTFChasis3 = new javax.swing.JTextField();
        jTFAsientos3 = new javax.swing.JTextField();
        jTFCapacidad3 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jCBTipo3 = new javax.swing.JComboBox();
        jCBRuta3 = new javax.swing.JComboBox();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Reclamo"));

        jPanel7.setLayout(null);

        jPanel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.setLayout(null);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Pasajero");
        jPanel8.add(jLabel11);
        jLabel11.setBounds(0, 170, 90, 30);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Codigo");
        jPanel8.add(jLabel12);
        jLabel12.setBounds(0, 10, 80, 30);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Descripcion");
        jPanel8.add(jLabel13);
        jLabel13.setBounds(-10, 50, 120, 30);
        jPanel8.add(jTFCod1);
        jTFCod1.setBounds(100, 10, 180, 30);

        jBLimpiar1.setText("Limpiar");
        jBLimpiar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiar1ActionPerformed(evt);
            }
        });
        jPanel8.add(jBLimpiar1);
        jBLimpiar1.setBounds(100, 270, 70, 23);

        jBCrear1.setText("Crear");
        jBCrear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCrear1ActionPerformed(evt);
            }
        });
        jPanel8.add(jBCrear1);
        jBCrear1.setBounds(220, 270, 59, 23);

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Estacion");
        jPanel8.add(jLabel28);
        jLabel28.setBounds(0, 220, 90, 30);

        jCBPasajero1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Troncal", "Alimentador", "Padron" }));
        jPanel8.add(jCBPasajero1);
        jCBPasajero1.setBounds(100, 170, 180, 30);

        jCBEstacion1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));
        jCBEstacion1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jCBEstacion1PopupMenuWillBecomeVisible(evt);
            }
        });
        jPanel8.add(jCBEstacion1);
        jCBEstacion1.setBounds(100, 220, 180, 30);

        jTADescripcion1.setColumns(20);
        jTADescripcion1.setRows(5);
        jScrollPane2.setViewportView(jTADescripcion1);

        jPanel8.add(jScrollPane2);
        jScrollPane2.setBounds(100, 60, 180, 96);

        jPanel7.add(jPanel8);
        jPanel8.setBounds(0, 0, 340, 310);

        jTPBus.addTab("Crear", jPanel7);

        jPanel3.setLayout(null);

        jPanel9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel9.setLayout(null);

        jBLimpiarConsultar.setText("Limpiar");
        jBLimpiarConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarConsultarActionPerformed(evt);
            }
        });
        jPanel9.add(jBLimpiarConsultar);
        jBLimpiarConsultar.setBounds(290, 100, 90, 23);

        jTResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Pasajero", "Estacion", "Descripcion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTResultados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTResultadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTResultados);

        jPanel9.add(jScrollPane1);
        jScrollPane1.setBounds(20, 200, 410, 100);

        jBConsultar1.setText("Consultar");
        jBConsultar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsultar1ActionPerformed(evt);
            }
        });
        jPanel9.add(jBConsultar1);
        jBConsultar1.setBounds(290, 140, 90, 23);

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Codigo");
        jPanel9.add(jLabel14);
        jLabel14.setBounds(0, 10, 80, 30);
        jPanel9.add(jTFCod2);
        jTFCod2.setBounds(100, 10, 180, 30);

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Pasajero");
        jPanel9.add(jLabel15);
        jLabel15.setBounds(0, 50, 90, 30);

        jCBPasajero2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Troncal", "Alimentador", "Padron" }));
        jPanel9.add(jCBPasajero2);
        jCBPasajero2.setBounds(100, 50, 180, 30);

        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Estacion");
        jPanel9.add(jLabel31);
        jLabel31.setBounds(0, 100, 90, 30);

        jCBEstacion2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));
        jCBEstacion2.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jCBEstacion2PopupMenuWillBecomeVisible(evt);
            }
        });
        jPanel9.add(jCBEstacion2);
        jCBEstacion2.setBounds(100, 100, 180, 30);

        jPanel3.add(jPanel9);
        jPanel9.setBounds(0, 0, 590, 340);

        jTPBus.addTab("Consultar", jPanel3);

        jPanel4.setLayout(null);

        jPanel10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel10.setLayout(null);

        jBModificar.setText("Modificar");
        jBModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarActionPerformed(evt);
            }
        });
        jPanel10.add(jBModificar);
        jBModificar.setBounds(170, 270, 110, 23);

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Placa");
        jPanel10.add(jLabel24);
        jLabel24.setBounds(-10, 10, 80, 30);

        jTFPlaca3.setEditable(false);
        jPanel10.add(jTFPlaca3);
        jTFPlaca3.setBounds(100, 10, 180, 30);
        jPanel10.add(jTFMarca3);
        jTFMarca3.setBounds(100, 50, 180, 30);

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Marca");
        jPanel10.add(jLabel25);
        jLabel25.setBounds(-30, 50, 120, 30);

        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Nro. Chasis");
        jPanel10.add(jLabel26);
        jLabel26.setBounds(-10, 90, 110, 30);
        jPanel10.add(jTFChasis3);
        jTFChasis3.setBounds(100, 90, 180, 30);
        jPanel10.add(jTFAsientos3);
        jTFAsientos3.setBounds(100, 130, 50, 30);
        jPanel10.add(jTFCapacidad3);
        jTFCapacidad3.setBounds(230, 130, 50, 30);

        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Nro. Asientos");
        jPanel10.add(jLabel29);
        jLabel29.setBounds(10, 130, 80, 40);

        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Tipo");
        jPanel10.add(jLabel30);
        jLabel30.setBounds(0, 170, 60, 30);

        jCBTipo3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Troncal", "Alimentador", "Padron" }));
        jPanel10.add(jCBTipo3);
        jCBTipo3.setBounds(100, 170, 180, 30);

        jCBRuta3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cargar" }));
        jCBRuta3.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jCBRuta3PopupMenuWillBecomeVisible(evt);
            }
        });
        jCBRuta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBRuta3ActionPerformed(evt);
            }
        });
        jPanel10.add(jCBRuta3);
        jCBRuta3.setBounds(100, 220, 180, 30);

        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("Ruta");
        jPanel10.add(jLabel35);
        jLabel35.setBounds(-10, 220, 90, 30);

        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("Capacidad");
        jPanel10.add(jLabel36);
        jLabel36.setBounds(150, 130, 80, 40);

        jPanel4.add(jPanel10);
        jPanel10.setBounds(0, 10, 450, 320);

        jTPBus.addTab("Modificar", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTPBus, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTPBus, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBLimpiar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiar1ActionPerformed
        jTFCod1.setText("");
        jTADescripcion1.setText("");
        jCBPasajero1.setSelectedIndex(0);
        jCBEstacion1.setSelectedIndex(0);
    }//GEN-LAST:event_jBLimpiar1ActionPerformed

    private void jBCrear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCrear1ActionPerformed

        int guardar = -1;
        try {

            String placa = jTFPlaca1.getText();
            String marca = jTFMarca1.getText();
            String chasis = jTFChasis1.getText();
            String tipo = jCBPasajero1.getSelectedItem().toString();
            int asientos = Integer.parseInt(jTFAsientos1.getText());
            int capacidad = Integer.parseInt(jTFCapacidad1.getText());
            String r = jCBEstacion1.getSelectedItem().toString();
            Rutas ruta = controladorRuta.consultar(r);
            guardar = controladorBus.insertar(placa, marca, chasis, tipo, asientos, capacidad, ruta);

        } catch (Exception e) {
        }
        if (guardar == -1) {
            JOptionPane.showMessageDialog(this, "No se pudo crear ", "Error Base Datos", JOptionPane.ERROR_MESSAGE);
        } else {

            if (guardar == 1) {

                JOptionPane.showMessageDialog(this, "Ya existe el Bus ", "Error", ERROR);


            } else {
                JOptionPane.showMessageDialog(this, "Bus Creado correctamente", "Sistema", JOptionPane.INFORMATION_MESSAGE);

                limpiarCamposConsultar();
                jTFPlaca2.setText(jTFPlaca1.getText());
                jBConsultar1.doClick();
                jTPBus.setSelectedIndex(1);
                limpiarCamposCrear();
            }
        }
    }//GEN-LAST:event_jBCrear1ActionPerformed

    private void jCBEstacion1PopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jCBEstacion1PopupMenuWillBecomeVisible
        jCBEstacion1.setModel(
                new javax.swing.DefaultComboBoxModel(controladorRuta.listar()));
    }//GEN-LAST:event_jCBEstacion1PopupMenuWillBecomeVisible

    private void jBLimpiarConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarConsultarActionPerformed
        limpiarCamposConsultar();
    }//GEN-LAST:event_jBLimpiarConsultarActionPerformed

    private void jTResultadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTResultadosMouseClicked

        int selectedRow = jTResultados.getSelectedRow();
        jCBRuta3.setModel(
                new javax.swing.DefaultComboBoxModel(controladorRuta.listar()));
        jTFPlaca3.setText("" + jTResultados.getModel().getValueAt(selectedRow, 0));
        jTFMarca3.setText("" + jTResultados.getModel().getValueAt(selectedRow, 1));
        jTFChasis3.setText("" + jTResultados.getModel().getValueAt(selectedRow, 2));
        jCBTipo3.setSelectedItem("" + jTResultados.getModel().getValueAt(selectedRow, 3));
        jTFAsientos3.setText("" + jTResultados.getModel().getValueAt(selectedRow, 4));
        jTFCapacidad3.setText("" + jTResultados.getModel().getValueAt(selectedRow, 5));
        jCBRuta3.setSelectedItem("" + jTResultados.getModel().getValueAt(selectedRow, 6));


        jTPBus.setSelectedIndex(2);
    }//GEN-LAST:event_jTResultadosMouseClicked

    private void jBConsultar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsultar1ActionPerformed
        LinkedList consulta = new LinkedList();

        try {
            int capacidad = 0;
            try {
                capacidad = Integer.parseInt(jTFCapacidad2.getText());
            } catch (Exception e) {
                capacidad = 0;
            }
            String ruta = jCBRuta2.getSelectedItem().toString();

            consulta = controladorBus.consultar(
                    jTFPlaca2.getText(),
                    jCBTipo2.getSelectedItem().toString(),
                    capacidad,
                    ruta);

            Object[][] s = new Object[consulta.size()][7];
            for (int i = 0; i < consulta.size(); i++) {
                Buses bus = (Buses) consulta.get(i);
                if (bus.getPlaca() != null) {
                    s[i][0] = bus.getPlaca();
                    s[i][1] = bus.getMarca();
                    s[i][2] = bus.getNroChasis();
                    s[i][3] = bus.getTipo();
                    s[i][4] = bus.getNroAsientos();
                    s[i][5] = bus.getCapacidad();
                    s[i][6] = bus.getRuta();

                } else {
                    s = null;
                }
            }
            TableModel myModel = new DefaultTableModel(s, new String[]{
                        "Placa", "Marca", "Chasis",
                        "Tipo", "Nro. Asientos", "Capacidad", "Ruta"}) {

                boolean[] canEdit = new boolean[]{false, false, false, false, false, false, false};

                @Override
                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit[columnIndex];
                }
            };
            ///remover filas
            jTResultados.setModel(myModel);
            jTResultados.setRowSorter(new TableRowSorter(myModel));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jBConsultar1ActionPerformed

    private void jBModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarActionPerformed
        int editar = -1;

        try {

            Rutas r = controladorRuta.consultar(jCBRuta3.getSelectedItem().toString());
            editar = controladorBus.modificar(
                    jTFPlaca3.getText(),
                    jTFMarca3.getText(),
                    jTFChasis3.getText(),
                    jCBTipo3.getSelectedItem().toString(),
                    Integer.parseInt(jTFAsientos3.getText()),
                    Integer.parseInt(jTFCapacidad3.getText()),
                    r);


        } catch (Exception e) {
            System.out.print(e);
        }
        if (editar == -1) {
            JOptionPane.showMessageDialog(this, "No su pudo modificar", "Error Base Datos", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "modificado correctamente", "Base Datos", JOptionPane.INFORMATION_MESSAGE);
            limpiarCamposConsultar();
            jTResultados.removeAll();
            jTFPlaca2.setText(jTFPlaca3.getText());
            jBConsultar1.doClick();
            jTPBus.setSelectedIndex(1);
            limpiarCamposModificar();
        }
    }//GEN-LAST:event_jBModificarActionPerformed

    private void jCBRuta3PopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jCBRuta3PopupMenuWillBecomeVisible
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBRuta3PopupMenuWillBecomeVisible

    private void jCBRuta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBRuta3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBRuta3ActionPerformed

    private void jCBEstacion2PopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jCBEstacion2PopupMenuWillBecomeVisible
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBEstacion2PopupMenuWillBecomeVisible

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBConsultar1;
    private javax.swing.JButton jBCrear1;
    private javax.swing.JButton jBLimpiar1;
    private javax.swing.JButton jBLimpiarConsultar;
    private javax.swing.JButton jBModificar;
    private javax.swing.JComboBox jCBEstacion1;
    private javax.swing.JComboBox jCBEstacion2;
    private javax.swing.JComboBox jCBPasajero1;
    private javax.swing.JComboBox jCBPasajero2;
    private javax.swing.JComboBox jCBRuta3;
    private javax.swing.JComboBox jCBTipo3;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTADescripcion1;
    private javax.swing.JTextField jTFAsientos3;
    private javax.swing.JTextField jTFCapacidad3;
    private javax.swing.JTextField jTFChasis3;
    private javax.swing.JTextField jTFCod1;
    private javax.swing.JTextField jTFCod2;
    private javax.swing.JTextField jTFMarca3;
    private javax.swing.JTextField jTFPlaca3;
    private javax.swing.JTabbedPane jTPBus;
    private javax.swing.JTable jTResultados;
    // End of variables declaration//GEN-END:variables
}
