/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import reportes.GenerarReporte;

/**
 *
 * @author chokuno
 */
public class JPReportes extends javax.swing.JPanel {

    /**
     * Creates new form JPReportes
     */
    GenerarReporte generadorReportes;
    public JPReportes() {
        initComponents();
        generadorReportes= new GenerarReporte();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBPasajeros = new javax.swing.JButton();
        jBPasajeroMovil = new javax.swing.JButton();
        jBTarjetasVen = new javax.swing.JButton();
        jBQuejas = new javax.swing.JButton();
        jBBuses = new javax.swing.JButton();
        jBRutas = new javax.swing.JButton();
        jBQuejasComun = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Reportes")));

        jBPasajeros.setText("Pasajeros");
        jBPasajeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPasajerosActionPerformed(evt);
            }
        });

        jBPasajeroMovil.setText("Pasajeros Movilizados");
        jBPasajeroMovil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPasajeroMovilActionPerformed(evt);
            }
        });

        jBTarjetasVen.setText("Tarjetas Vendidas");
        jBTarjetasVen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTarjetasVenActionPerformed(evt);
            }
        });

        jBQuejas.setText("Quejas y/o Reclamos");
        jBQuejas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBQuejasActionPerformed(evt);
            }
        });

        jBBuses.setText("Buses Padrones");
        jBBuses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBusesActionPerformed(evt);
            }
        });

        jBRutas.setText("Rutas");
        jBRutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRutasActionPerformed(evt);
            }
        });

        jBQuejasComun.setText("Quejas Comunes");
        jBQuejasComun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBQuejasComunActionPerformed(evt);
            }
        });

        jLabel1.setText("Listado de pasajeros con tarjetas personalizadas");

        jLabel2.setText("Listado de pasajeros movilizados por ruta y estacion");

        jLabel3.setText("Listado de ganacias de cada estacion por tarjetas vendidas");

        jLabel4.setText("Listado de las rutas");

        jLabel5.setText("Listado de las quejas y los reclamos");

        jLabel6.setText("Listado de los buses padrones y los conductores asociados");

        jLabel7.setText("Diagrama de Pastel mostrando las quejas mas comunes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBPasajeroMovil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBTarjetasVen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBQuejas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBBuses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBRutas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBQuejasComun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBPasajeros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBPasajeros)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBPasajeroMovil)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBTarjetasVen)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBQuejas)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBBuses)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBRutas)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBQuejasComun)
                    .addComponent(jLabel7))
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBPasajerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPasajerosActionPerformed
        // TODO add your handling code here:
        generadorReportes.generarReporte("pasajeros");
        
    }//GEN-LAST:event_jBPasajerosActionPerformed

    private void jBPasajeroMovilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPasajeroMovilActionPerformed
        // TODO add your handling code here:
        generadorReportes.generarReporte("pasajerosMovilizados");
    }//GEN-LAST:event_jBPasajeroMovilActionPerformed

    private void jBTarjetasVenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTarjetasVenActionPerformed
        // TODO add your handling code here:
        generadorReportes.generarReporte("tarjetasVendidas");
    }//GEN-LAST:event_jBTarjetasVenActionPerformed

    private void jBQuejasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBQuejasActionPerformed
        // TODO add your handling code here:
        generadorReportes.generarReporte("quejas");
    }//GEN-LAST:event_jBQuejasActionPerformed

    private void jBBusesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBusesActionPerformed
        // TODO add your handling code here:
        generadorReportes.generarReporte("buses");
    }//GEN-LAST:event_jBBusesActionPerformed

    private void jBRutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRutasActionPerformed
        // TODO add your handling code here:
        generadorReportes.generarReporte("rutas");
    }//GEN-LAST:event_jBRutasActionPerformed

    private void jBQuejasComunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBQuejasComunActionPerformed
        // TODO add your handling code here:
        generadorReportes.generarReporte("quejasComunes");
    }//GEN-LAST:event_jBQuejasComunActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuses;
    private javax.swing.JButton jBPasajeroMovil;
    private javax.swing.JButton jBPasajeros;
    private javax.swing.JButton jBQuejas;
    private javax.swing.JButton jBQuejasComun;
    private javax.swing.JButton jBRutas;
    private javax.swing.JButton jBTarjetasVen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
