/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import controladores.ControladorRuta;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import entidades.Rutas;

/**
 *
 * @author juandapp
 */
public class JPRuta extends javax.swing.JPanel {

    /**
     * Creates new form JPCliente
     */
    ControladorRuta rutaControlador;
     int selectedRow;

    public JPRuta() {
        initComponents();

        rutaControlador = new ControladorRuta();


        jTabbedPane1.setSelectedIndex(0);   
        

        

    }
     public JPRuta(int tipo) {
        initComponents();

        rutaControlador = new ControladorRuta();


        jTabbedPane1.setSelectedIndex(1);
        jTabbedPane1.setEnabledAt(0, false);   
        jTabbedPane1.setEnabledAt(2, false);   
        

        

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTFNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTPDescripcion = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        jBLimpiarCrear = new javax.swing.JButton();
        jBCrear = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jBConsultar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTFNombre2 = new javax.swing.JTextField();
        jTFDescripcion2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jBLimpiarConsultar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTResultados = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jBModificar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTFNombre3 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTPDescripcion1 = new javax.swing.JTextPane();

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Ruta"));
        jPanel4.setLayout(null);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTFNombre.setColumns(20);
        jPanel1.add(jTFNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        jLabel2.setText("Nombre");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jScrollPane2.setViewportView(jTPDescripcion);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 270, 72));

        jLabel4.setText("Descripcion");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jBLimpiarCrear.setText("Limpiar");
        jBLimpiarCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarCrearActionPerformed(evt);
            }
        });
        jPanel1.add(jBLimpiarCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 80, -1));

        jBCrear.setText("Crear");
        jBCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCrearActionPerformed(evt);
            }
        });
        jPanel1.add(jBCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 70, -1));

        jTabbedPane1.addTab("Crear", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBConsultar.setText("Consultar");
        jBConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsultarActionPerformed(evt);
            }
        });
        jPanel2.add(jBConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 90, -1));

        jLabel5.setText("Nombre");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jTFNombre2.setColumns(20);
        jPanel2.add(jTFNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        jTFDescripcion2.setColumns(20);
        jPanel2.add(jTFDescripcion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        jLabel6.setText("Descripcion");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jBLimpiarConsultar.setText("Limpiar");
        jBLimpiarConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarConsultarActionPerformed(evt);
            }
        });
        jPanel2.add(jBLimpiarConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 90, -1));

        jTResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Descripcion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTResultados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTResultadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTResultados);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 420, 120));

        jTabbedPane1.addTab("Consultar", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBModificar.setText("Modificar");
        jBModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarActionPerformed(evt);
            }
        });
        jPanel3.add(jBModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 90, -1));

        jLabel7.setText("Nombre");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jTFNombre3.setColumns(20);
        jTFNombre3.setEnabled(false);
        jPanel3.add(jTFNombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        jLabel15.setText("Descripcion");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jScrollPane3.setViewportView(jTPDescripcion1);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 270, 72));

        jTabbedPane1.addTab("Modificar", jPanel3);

        jPanel4.add(jTabbedPane1);
        jTabbedPane1.setBounds(10, 20, 524, 267);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarActionPerformed
        int editar = -1;
        try {
            editar = rutaControlador.modificar(jTFNombre3.getText(),
                    jTPDescripcion1.getText());
        } catch (Exception e) {
            System.out.print(e);
        }
        if (editar == -1) {
            JOptionPane.showMessageDialog(this, "No se pudo modificar la ruta", "Error Base Datos", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Ruta modificado correctamente", "Base Datos", JOptionPane.INFORMATION_MESSAGE);
            limpiarCamposConsultar();
            jTFNombre2.setText(jTFNombre3.getText());
            jBConsultar.doClick();
            jTabbedPane1.setSelectedIndex(1);
            limpiarCamposModificar();
        }
    }//GEN-LAST:event_jBModificarActionPerformed

    private void jBLimpiarCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarCrearActionPerformed
        limpiarCamposCrear();
    }//GEN-LAST:event_jBLimpiarCrearActionPerformed

    private void jBCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCrearActionPerformed
        int guardar = -1;
        try {
            guardar = rutaControlador.insertar(
                    jTFNombre.getText(),
                    jTPDescripcion.getText());

        } catch (Exception e) {
        }

        if (guardar == -1) {
            JOptionPane.showMessageDialog(this, "No se pudo crear la Ruta", "Error Base Datos", JOptionPane.ERROR_MESSAGE);
        } else {
            if (guardar == 1) {
                JOptionPane.showMessageDialog(this, "Ya existe la Ruta", "Error Base Datos", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Ruta Creada correctamente", "Sistema", JOptionPane.INFORMATION_MESSAGE);
                limpiarCamposConsultar();
                jTFNombre2.setText(jTFNombre.getText());
                jBConsultar.doClick();
                jBLimpiarCrear.doClick();
                jTabbedPane1.setSelectedIndex(1);

            }
        }


    }//GEN-LAST:event_jBCrearActionPerformed

    private void jBConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsultarActionPerformed

        LinkedList consulta = new LinkedList();
        try {
            consulta = rutaControlador.consultar(jTFNombre2.getText(), jTFDescripcion2.getText());
            Object[][] s = new Object[consulta.size()][2];
            for (int i = 0; i < consulta.size(); i++) {
                Rutas ruta = (Rutas) consulta.get(i);
                if (ruta.getNombre() != null) {
                    s[i][0] = ruta.getNombre();
                    s[i][1] = ruta.getDescripcion();

                } else {
                    s = null;
                }
            }
            TableModel myModel = new DefaultTableModel(s, new String[]{"Nombre", "Descripcion"}) {

                boolean[] canEdit = new boolean[]{false, false
                };

                @Override
                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit[columnIndex];
                }
            };
            
            ///remover filas
            jTResultados.setModel(myModel);
            jTResultados.setRowSorter(new TableRowSorter(myModel));

            
        }catch(Exception e)
        {e.printStackTrace();}
       
    }//GEN-LAST:event_jBConsultarActionPerformed

    private void limpiarCamposModificar() {
        jTFNombre3.setText("");
        jTPDescripcion1.setText("");
    }

    private void limpiarCamposCrear() {
        jTPDescripcion.setText("");
        jTFNombre.setText("");

    }

    private void limpiarCamposConsultar() {
        jTFDescripcion2.setText("");
        jTFNombre2.setText("");
    }

    private void jBLimpiarConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarConsultarActionPerformed
        limpiarCamposConsultar();
        jBConsultar.doClick();
    }//GEN-LAST:event_jBLimpiarConsultarActionPerformed

    private void jTResultadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTResultadosMouseClicked

        int selectedRow = jTResultados.getSelectedRow();
        jTFNombre3.setText("" + jTResultados.getModel().getValueAt(selectedRow, 0));
        jTPDescripcion1.setText("" + jTResultados.getModel().getValueAt(selectedRow, 1));
        


        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jTResultadosMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBConsultar;
    private javax.swing.JButton jBCrear;
    private javax.swing.JButton jBLimpiarConsultar;
    private javax.swing.JButton jBLimpiarCrear;
    private javax.swing.JButton jBModificar;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTFDescripcion2;
    private javax.swing.JTextField jTFNombre;
    private javax.swing.JTextField jTFNombre2;
    private javax.swing.JTextField jTFNombre3;
    private javax.swing.JTextPane jTPDescripcion;
    private javax.swing.JTextPane jTPDescripcion1;
    private javax.swing.JTable jTResultados;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
