/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import controladores.ControladorTarjetasPersonalizadas;
import entidades.TarjetasGenericas;
import entidades.TarjetasPersonalizadas;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Juan
 */
public class JPTarjetasPersonalizadas extends javax.swing.JPanel {

    /**
     * Creates new form JPTarjetasPersonalizadas
     */
    
    ControladorTarjetasPersonalizadas controladorTarjetasPersonalizadas;
    public JPTarjetasPersonalizadas() {
        initComponents();
        controladorTarjetasPersonalizadas=new ControladorTarjetasPersonalizadas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTPTarjetasPersonalizadas = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jTFNumeroPasajes2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jBLimpiarCrear2 = new javax.swing.JButton();
        jBCrear = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTFPinTarjeta = new javax.swing.JTextField();
        jCEstado = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jBConsultar = new javax.swing.JButton();
        jBLimpiarConsultar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTResultados = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jTFPinTarjeta1 = new javax.swing.JTextField();
        jTFNumeroPasajes3 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        JCEstado1 = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        jBModificar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jTFPinTarjeta2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTFNumeroPasajes4 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        JCEstado2 = new javax.swing.JComboBox();
        jTFAdelantos3 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Tarjeta Personalizada"));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTFNumeroPasajes2.setColumns(20);
        jPanel3.add(jTFNumeroPasajes2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        jLabel6.setText("Pin Tarjeta");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel7.setText("Estado");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jBLimpiarCrear2.setText("Limpiar");
        jBLimpiarCrear2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarCrear2ActionPerformed(evt);
            }
        });
        jPanel3.add(jBLimpiarCrear2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 80, -1));

        jBCrear.setText("Crear");
        jBCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCrearActionPerformed(evt);
            }
        });
        jPanel3.add(jBCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 70, -1));

        jLabel8.setText("Saldo");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jTFPinTarjeta.setColumns(20);
        jPanel3.add(jTFPinTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, 30));

        jCEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Disponible" }));
        jPanel3.add(jCEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 200, -1));

        jTPTarjetasPersonalizadas.addTab("Crear", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBConsultar.setText("Consultar");
        jBConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsultarActionPerformed(evt);
            }
        });
        jPanel4.add(jBConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 90, -1));

        jBLimpiarConsultar.setText("Limpiar");
        jBLimpiarConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarConsultarActionPerformed(evt);
            }
        });
        jPanel4.add(jBLimpiarConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 90, -1));

        jTResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pin Tarjeta", "Saldo", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTResultados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTResultadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTResultados);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 420, 120));

        jLabel9.setText("Pin Tarjeta");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jTFPinTarjeta1.setColumns(20);
        jPanel4.add(jTFPinTarjeta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 210, 30));

        jTFNumeroPasajes3.setColumns(20);
        jPanel4.add(jTFNumeroPasajes3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 210, -1));

        jLabel10.setText("saldo");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 90, -1));

        jLabel11.setText("Estado");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        JCEstado1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Disponible", "Vendida" }));
        jPanel4.add(JCEstado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 200, -1));

        jTPTarjetasPersonalizadas.addTab("Consultar", jPanel4);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBModificar.setText("Modificar");
        jBModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarActionPerformed(evt);
            }
        });
        jPanel5.add(jBModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 90, -1));

        jLabel12.setText("Pin Tarjeta");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jTFPinTarjeta2.setColumns(20);
        jTFPinTarjeta2.setEnabled(false);
        jPanel5.add(jTFPinTarjeta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 210, 30));

        jLabel13.setText("Numero de Pasajes");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jTFNumeroPasajes4.setColumns(20);
        jPanel5.add(jTFNumeroPasajes4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 210, -1));

        jLabel14.setText("Adelantos Disponibles");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 120, -1));

        JCEstado2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Disponible", "Vendido" }));
        JCEstado2.setEnabled(false);
        jPanel5.add(JCEstado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 200, -1));
        jPanel5.add(jTFAdelantos3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 210, -1));

        jLabel15.setText("Estado");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jTPTarjetasPersonalizadas.addTab("Modificar", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTPTarjetasPersonalizadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 358, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(35, Short.MAX_VALUE)
                    .addComponent(jTPTarjetasPersonalizadas, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBLimpiarCrear2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarCrear2ActionPerformed
        // TODO add your handling code here:
        jTFPinTarjeta.setText("");
        jTFNumeroPasajes2.setText("");
        jCEstado.setSelectedIndex(0);
    }//GEN-LAST:event_jBLimpiarCrear2ActionPerformed

    private void jBCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCrearActionPerformed
        // TODO add your handling code here:
        int guardar = -1;

        try {
            guardar = controladorTarjetasPersonalizadas.insertar(
                    jTFPinTarjeta.getText(),
                    Integer.parseInt(jTFNumeroPasajes2.getText()),
                    jCEstado.getSelectedItem().toString());

        } catch (Exception e) {
        }

        if (guardar == -1) {
            JOptionPane.showMessageDialog(this, "No se pudo crear la tarjeta ", "Error Base Datos", JOptionPane.ERROR_MESSAGE);
        } else {
            if (guardar == 1) {
                JOptionPane.showMessageDialog(this, "Ya existe la tarjeta ", "Error Base Datos", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Tarjeta  Creada correctamente", "Sistema", JOptionPane.INFORMATION_MESSAGE);
                jBLimpiarConsultar.doClick();
                jTFPinTarjeta1.setText(jTFPinTarjeta.getText());
                jBLimpiarCrear2.doClick();
                jTPTarjetasPersonalizadas.setSelectedIndex(1);
                jBConsultar.doClick();

            }
        }
    }//GEN-LAST:event_jBCrearActionPerformed

    private void jBConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsultarActionPerformed
        // TODO add your handling code here:
        LinkedList consulta = new LinkedList();
        try {


            int num_pasaje = 0;

            try {
                num_pasaje = Integer.parseInt(jTFNumeroPasajes3.getText());
            } catch (Exception e) {
                num_pasaje = 0;
            }

            System.out.println(num_pasaje);
            consulta = controladorTarjetasPersonalizadas.consultar(jTFPinTarjeta1.getText(),
                    num_pasaje, JCEstado1.getSelectedItem().toString());

            Object[][] s = new Object[consulta.size()][4];
            for (int i = 0; i < consulta.size(); i++) {
                TarjetasPersonalizadas tg = (TarjetasPersonalizadas) consulta.get(i);
                if (tg.getPinTarjeta() != null) {
                    s[i][0] = tg.getPinTarjeta();
                    s[i][1] = tg.getNroPasajes();
                    s[i][2] = tg.getEstado();
                    s[i][3] = tg.getAdelantoDisponible();

                } else {
                    s = null;
                }
            }
            TableModel myModel = new DefaultTableModel(s, new String[]{"Pin Tarjeta", "Saldo", "Estado", "Adelantos Disponibles"}) {

                boolean[] canEdit = new boolean[]{false, false, false, false
                };

                @Override
                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit[columnIndex];
                }
            };

            ///remover filas
            jTResultados.setModel(myModel);
            jTResultados.setRowSorter(new TableRowSorter(myModel));


        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jBConsultarActionPerformed

    private void jBLimpiarConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarConsultarActionPerformed
        // TODO add your handling code here:
        jTFPinTarjeta1.setText("");
        jTFNumeroPasajes3.setText("");
        JCEstado1.setSelectedIndex(0);
        jBConsultar.doClick();

    }//GEN-LAST:event_jBLimpiarConsultarActionPerformed

    private void jTResultadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTResultadosMouseClicked
        // TODO add your handling code here:
        int selectedRow = jTResultados.getSelectedRow();
        jTFPinTarjeta2.setText("" + jTResultados.getModel().getValueAt(selectedRow, 0));
        jTFNumeroPasajes4.setText("" + jTResultados.getModel().getValueAt(selectedRow, 1));
        JCEstado2.setSelectedItem("" + jTResultados.getModel().getValueAt(selectedRow, 2));
        jTFAdelantos3.setText("" + jTResultados.getModel().getValueAt(selectedRow, 3));

        jTPTarjetasPersonalizadas.setSelectedIndex(2);
    }//GEN-LAST:event_jTResultadosMouseClicked

    private void jBModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarActionPerformed
        // TODO add your handling code here:
        int editar = -1;
        try {

            int num_pasaje = 0;
            int adelantos=0;

            try {
                num_pasaje = Integer.parseInt(jTFNumeroPasajes4.getText());
            } catch (Exception e) {
                num_pasaje = 0;
            }
            
            try {
                adelantos = Integer.parseInt(jTFAdelantos3.getText());
            } catch (Exception e) {
                adelantos = 0;
            }
            editar = controladorTarjetasPersonalizadas.modificar(
                    jTFPinTarjeta2.getText(),
                    num_pasaje,
                    JCEstado2.getSelectedItem().toString(), adelantos);
        } catch (Exception e) {
            System.out.print(e);
        }
        if (editar == -1) {
            JOptionPane.showMessageDialog(this, "No se pudo modificar la tarjeta ", "Error Base Datos", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Tarjeta  modificada correctamente", "Base Datos", JOptionPane.INFORMATION_MESSAGE);
            jBLimpiarConsultar.doClick();
            jTFPinTarjeta1.setText(jTFPinTarjeta2.getText());
            jBConsultar.doClick();
            jTPTarjetasPersonalizadas.setSelectedIndex(1);
           
        }

    }//GEN-LAST:event_jBModificarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox JCEstado1;
    private javax.swing.JComboBox JCEstado2;
    private javax.swing.JButton jBConsultar;
    private javax.swing.JButton jBCrear;
    private javax.swing.JButton jBLimpiarConsultar;
    private javax.swing.JButton jBLimpiarCrear2;
    private javax.swing.JButton jBModificar;
    private javax.swing.JComboBox jCEstado;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFAdelantos3;
    private javax.swing.JTextField jTFNumeroPasajes2;
    private javax.swing.JTextField jTFNumeroPasajes3;
    private javax.swing.JTextField jTFNumeroPasajes4;
    private javax.swing.JTextField jTFPinTarjeta;
    private javax.swing.JTextField jTFPinTarjeta1;
    private javax.swing.JTextField jTFPinTarjeta2;
    private javax.swing.JTabbedPane jTPTarjetasPersonalizadas;
    private javax.swing.JTable jTResultados;
    // End of variables declaration//GEN-END:variables
}
